<?PHP     

	/**
	 * 
	 * delete.php english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("DELETE_TEMPLATE_NOT_CREATOR", "Sorry you aren't the creator of this project and as such cannot delete it");
	
	define("DELETE_TEMPLATE_SYNDICATED", "Sorry you cannot delete a syndicated project. To delete this project, first turn off syndication in the project's properties.");
	

?>