<?PHP    

	/**
	 * 
	 * duplicate_template.php english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("COPY_OF", "Copy of ");
	define("DUPLICATE_TEMPLATE_NOT_CREATOR", "Only project creators or co-authors can duplicate a project");
	define("NO_PERMISSION_TO_DUPLICATE_TEMPLATE_OF_FOLDER", "You don't have permission to duplicate '{0}' of folder '{1}'");


