<?PHP

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("MANAGEMENT_LIBRARY_REMOVE", "Usuń");
	define("MANAGEMENT_LIBRARY_VIEW", "Pokaż");

	define("MANAGEMENT_LIBRARY_ADD_CATEGORY", "Dodaj nową kategorię");
	define("MANAGEMENT_LIBRARY_NEW_CATEGORY", "Nowa kategoria to");
	define("MANAGEMENT_LIBRARY_NEW_CATEGORY_NAME", "Wprowadź nazwę tutaj");
	define("MANAGEMENT_LIBRARY_NEW_LABEL", "Dodaj");
	define("MANAGEMENT_LIBRARY_EXISTING_CATEGORIES", "Zarządzaj istniejącymi kategoriami");

	define("MANAGEMENT_LIBRARY_REMOVE_RSS", "Usuń z RSS");
	define("MANAGEMENT_LIBRARY_REMOVE_EXPORT", "Usuń z eksportu");
	define("MANAGEMENT_LIBRARY_REMOVE_SYNDICATION", "Usuń z syndykacji");

	define("MANAGEMENT_LIBRARY_ADD_SECURITY", "Dodaj nowe ustawienie");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY", "Nazwa ustawienia zabezpieczenia to ");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_NAME", "Wprowadź tutaj nazwę");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DATA", "Dane zabezpieczenia to ");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DETAILS", "Wprowadź adres www lub zakres IP");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_INFO", "Informacja zabezpieczenia to ");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DESCRIPTION", "`Wprowadź tutaj opis, który użytkownicy zobaczą");

	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY", "Zarządzaj istniejącymi ustawieniami");
		
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_IS", "Ustawienie bezpieczeństwa to ");
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_DATA", "Dane bezpieczeństwa to ");
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_INFO", "Informacja bezpieczeństwa to ");
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_REMOVE", "Usuń te ustawienie");
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_WARNING", "Przy usuwaniu ustawienia, cała zawartość z tą opcją będzie ustawiona na Prywatny. Powinieś pierwszy poinformować użytkowników o tej zmianie");
	
	define("MANAGEMENT_LIBRARY_NEW_LICENCE", "Dodaj nową licencję");
	define("MANAGEMENT_LIBRARY_NEW_LICENCE_DETAILS", "Nowa licencja to ");
	define("MANAGEMENT_LIBRARY_NEW_LICENCE_NAME", "Wprowadź tutaj nazwę licencji");
	define("MANAGEMENT_LIBRARY_MANAGE_LICENCES", "Zarządzaj istniejącymi licencjami");

	define("MANAGEMENT_LIBRARY_FAIL", "cecha jest tylko dla administratorów");

    define("MANAGEMENT_LIBRARY_ADD_LANGUAGE", "Dodaj lub zaktualizuj definicję języka");
    define("MANAGEMENT_LIBRARY_EXISTING_LANGUAGES", "Zarządzaj istniejącymi językami");
    define("MANAGEMENT_LIBRARY_LANGUAGE_INSTALL", "Instaluj definicję języka");
    define("MANAGEMENT_LIBRARY_LANGUAGES", "Ustawienia języka");
    define("MANAGEMENT_LIBRARY_LANGUAGES_EXPLAINED", "Załaduj i odśwież definicje języka używając poniższego przycisku. Nowe definicje języka możesz znaleźć i ściągnąć ze strony Społeczności Xerte (http://www.xerte.org.uk). Tam są 3 różne paczki. Możesz użyć którąkolwiek z nich.");
    define("MANAGEMENT_LIBRARY_LANGUAGES_UPDATED", "Definicje języka zostały zaktualizowane.");
?>