<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("MANAGEMENT_SITE_TITLE", "Ustawienia strony (HTML / Obrazy)");

	define("MANAGEMENT_SITE_URL", "URL strony to (to jest URL strony - zmiana tego nie zmiana URL) ");

	define("MANAGEMENT_SITE_TITLE_HTML", "Tytuł strony to (to jest zawartość tytułu tagu HTML) ");

	define("MANAGEMENT_SITE_NAME", "Nazwa strony to (jest częścią index.php i RSS i syndykowanych kanałów)");

	define("MANAGEMENT_SITE_LOGO", "Logo strony to (logo jest w lewym górnym rogu)");

	define("MANAGEMENT_SITE_LOGO_ORG", "Logo organizacji to (logo jest w prawym górnym rogu)");

	define("MANAGEMENT_SITE_WELCOME", "Wiadomość powitalna to (tekst nad narzędziami na index.php)");

	define("MANAGEMENT_SITE_TEXT", "Tekst strony to (tekst po prawej stronie narzędzi na index.php)");

	define("MANAGEMENT_SITE_NEWS", "Tekst wiadomości to (drugi strąk pod strąkiem logowania na index.php)");

	define("MANAGEMENT_SITE_POD_ONE", "Zawartość strąka nr 1 to (pierwszy strąk poniżej obszaru pliku na stronie po zalogowaniu)");

	define("MANAGEMENT_SITE_POD_TWO", "Zawartość strąka nr 2 to (drugi strąk poniżej obszaru pliku na stronie po zalogowaniu)");

	define("MANAGEMENT_SITE_COPYRIGHT", "Wiadomość praw autorskich to ");

	define("MANAGEMENT_SITE_DEMONSTRATION", "URL strony demonstracyjnej to ");

	define("MANAGEMENT_SITE_LOGIN_FORM", "Kod forumularza to (kod do uchwytu formatu HTML dla obszaru zalogowania)");

	define("MANAGEMENT_SITE_PEER_FORM", "Kod formularza wzajemnej oceny to (kod do uchwytu formatu HTML dla obszaru zalogowania wzajemnej oceny)");

	define("MANAGEMENT_SITE_FEEDBACK", "Lista odpowiedzi strony to (lista odpowiedzi strony to (lista adresów email oddzielonymi średnikami do otrzymywania odpowiedzi ze strony odpowiedzi zwrotnych)");

	define("MANAGEMENT_SITE_SERVER", "Ustawienia serwera ");
		
	define("MANAGEMENT_VIEW", "Pokaż");

	define("MANAGEMENT_SITE_HTACCESS", "Ustawienie HTACCESS to (czy używasz czy też nie pliku .htaccess na stronie)");

	define("MANAGEMENT_SITE_SESSION_NAME", "Nazwa sesji PHP to ");

	define("MANAGEMENT_SITE_MIME", "Dozwolone typy ładowanych plików multimedialnych i strony to ");

	define("MANAGEMENT_SITE_INTEGRATION", "Ścieżka do integracji to  ");

	define("MANAGEMENT_SITE_ADMIN_USER", "Nazwa admina to ");

	define("MANAGEMENT_SITE_ADMIN_PASSWORD", "Hasło admina to ");

	define("MANAGEMENT_SITE_RSS", "Ustawienia RSS ");

	define("MANAGEMENT_SITE_RSS_TITLE", "Tytuł kanału RSS to ");

	define("MANAGEMENT_SITE_RSS_PUBLISHER", "Wyświetlane w kanale syndykowanym instytucje publikujące to ");

	define("MANAGEMENT_SITE_RSS_RIGHTS", "Prawa standardowej syndykacji dla zawartości syndykowanej to ");

	define("MANAGEMENT_SITE_RSS_LICENCE", "Licencja standardowej syndykacji dla zawartości syndykowanej to ");

	define("MANAGEMENT_SITE_PATH", "Ustawienia ścieżki ");

	define("MANAGEMENT_SITE_PATH_MODULE", "Ścieżka modułu to ");

	define("MANAGEMENT_SITE_PATH_WEBSITE", "Ścieżka kodu strony to ");

	define("MANAGEMENT_SITE_PATH_SHORT", "Ścieżka krótkiego obszaru pliku to ");

	define("MANAGEMENT_SITE_PATH_LIBRARY", "Ścieżka biblioteki php to ");

	define("MANAGEMENT_SITE_PATH_ROOT", "Ścież apliku głównego to ");

	define("MANAGEMENT_SITE_PATH_IMPORT", "Ścieżka importu to ");

	define("MANAGEMENT_SITE_SQL", "Ustawienie zapytania SQL ");

	define("MANAGEMENT_SITE_QUERY", "Zapytanie odtwarzania, edycji, podglądu to ");
	
	define("MANAGEMENT_SITE_ERROR_HANDLING", "Ustawienia uchwytu błędu ");

	define("MANAGEMENT_SITE_ERROR_EMAIL", "Lista błędu email (konta do otrzymywania wiadomości email z dziennika błędów)");

	define("MANAGEMENT_SITE_ERROR_EMAIL_ACCOUNT", "Logowanie wiadomości błędu to (ustaw na true aby logować błędy)");

	define("MANAGEMENT_SITE_ERROR_MAX", "Max. rozmiar błędu to (max. liczba wpisów na logowany błąd)");

	define("MANAGEMENT_SITE_LDAP", "Ustawienia LDAP ");
	
	define("MANAGEMENT_SITE_LDAP_DELIMIT", "Możesz ustawić wiele hostów przez oddzielenie od siebie wpisów używając $$$ jako seperatora");

	define("MANAGEMENT_SITE_LDAP_HOST", "LDAP host to ");

	define("MANAGEMENT_SITE_LDAP_PORT", "LDAP port to ");

	define("MANAGEMENT_SITE_LDAP_PASSWORD", "LDAP hasło to "); 

	define("MANAGEMENT_SITE_LDAP_BASE", "LDAP base to ");

	define("MANAGEMENT_SITE_LDAP_BIND", "LDAP bind to ");

	define("MANAGEMENT_SITE_LDAP_FILTER_ONE", "LDAP główny filtr to ");

	define("MANAGEMENT_SITE_LDAP_FILTER_TWO", "LDAP drugi filtr to");

	define("MANAGEMENT_SITE_XERTE", "Ustawienia Xerte ");

	define("MANAGEMENT_SITE_XERTE_SAVE", "Ścieżka zapisu flash to ");

	define("MANAGEMENT_SITE_XERTE_UPLOAD", "Ścieżka załadowania flash to ");

	define("MANAGEMENT_SITE_XERTE_PREVIEW", "Ścieżka sprawdzania podglądu flash to ");

	define("MANAGEMENT_SITE_XERTE_SKIN", "Skórka flash flv to ");

	define("MANAGEMENT_SITE_EMAIL", "Email ");

	define("MANAGEMENT_SITE_EMAIL_ACCOUNT", "Konto email strony to (POTRZEBUJESZ to wypełnić, jeżeli chcesz włączyć odpowiedzi zwrotne i/lub wzajemną ocenianie.");

	define("MANAGEMENT_SITE_EMAIL_HEADERS", "Dodatkowe nagłówki emaila strony to (użyj symbolu * jako nową linię)");

	define("MANAGEMENT_SITE_EMAIL_SUFFIX", "Email strony do dodania użytkownika to ");

	define("MANAGEMENT_SITE_PROXY", "Proxy host strony to ");

	define("MANAGEMENT_SITE_PROXY_PORT", "Proxy port strony to ");

	define("MANAGEMENT_SITE_PROXY_EXPLAINED", "Przez bezpośrednią edycję pliku rss proxy.php (w głównym folderze), możesz dodać wedle swojego uznania dodać do 4 hostów i portów proxy.");

  define("MANAGEMENT_SITE_LTI","Ustawienia LTI");

define("LTI_TOGGLE","Pokaż");

define("LTI_KEYS_NAME","Opisowa nazwa klucza LTI");
define("LTI_KEYS_KEY","Klucz LTI");
define("LTI_KEYS_SECRET","Sekretne klucze LTI");
define("LTI_KEYS_CONTEXT_ID","nadpisanie dla kontekstu LTI");
define("LTI_KEYS_DELETED","Kiedy było to usuwane");
define("LTI_KEYS_UPDATED_ON","Kiedy było to ostatnio aktualizowane");

define("MANAGEMENT_SITE_LTI_KEYS","Klucze LTI");

define("LTI_KEYS_NEW","Nowy");
define("LTI_KEYS_DELETE","Usuń");
define("LTI_KEYS_ADD","Dodaj nowy klucz LTI");
define("LTI_KEYS_ADD_SUBMIT","Dodaj nowy klucz LTI");
define("LTI_KEYS_EDIT_SUBMIT","Zapisz klucz LTI");
define("LTI_KEYS_DELETE_SUBMIT","Usuń klucz LTI");

?>