<?PHP

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("TEMPLATE_UPLOAD", "Załaduj szablon");

	define("TEMPLATE_UPLOAD_BUTTON", "Załaduj");

	define("TEMPLATE_VIEW", "Pokaż");

    define("TEMPLATE_UPDATE_EXPLANATION", "Aby dodać szablon do swojej instalacji XOT, proszę załadować szablon używając FTP i nacisnąć poniższy przycisk, aby zaktualizować");

	define("TEMPLATE_UPDATE", "Zaktualizuj listę szablonów");
	
	define("TEMPLATE_MANAGE", "Zarządzaj istniejącymi szablonami");

	define("TEMPLATE_TYPE", "Ten szablon jest typu");
	
	define("TEMPLATE_INSTALL", " Ten szablon opiera się na module ");
	
	define("TEMPLATE_INSTALL_INST", " Proszę zainstalować ");

	define("TEMPLATE_VERSION", "Ten szablon ma nr wersji"); 

	define("TEMPLATE_DESCRIPTION", "Opis dla tego szablonu to"); 

	define("TEMPLATE_UPLOAD_DATE", "Ten szablon był aktualizowany");

	define("TEMPLATE_NAME", "Szablon ma poniższe nazwy dla użytkowników");

	define("TEMPLATE_EXAMPLE", "Szablon ma poniższy przykład (0 oznacza brak przykładu)");

	define("TEMPLATE_ACCESS", "Poniżsi użytkownicy mają dostęp do tego szablonu (* oznacza każdy)");

	define("TEMPLATE_DATE_UPLOAD", "Data załadowania tego szablonu to (wpływa to na kolejność ich wyświetlania / najpierw najnowsze");

	define("TEMPLATE_STATUS", "Ten szablon jest obecnie ustawiony jako");

	define("TEMPLATE_ACTIVE", "Aktywny");

	define("TEMPLATE_INACTIVE", "Nieaktywny");

	define("TEMPLATE_REPLACE", "Załaduj nową wersję tego szablonu");


?>