<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("USERS_MANAGEMENT_TEMPLATE_VIEW", "Pokaż");

	define("USERS_MANAGEMENT_TEMPLATE_ID", "Nr szablony to");

	define("USERS_MANAGEMENT_TEMPLATE_CREATED", "Data utworzenia to"); 

	define("USERS_MANAGEMENT_TEMPLATE_MODIFIED", "Data modyfikacji to"); 

	define("USERS_MANAGEMENT_TEMPLATE_ACCESSED", "Data dostępu to");

	define("USERS_MANAGEMENT_TEMPLATE_PLAYS", "Numer odtworzeń to"); 

	define("USERS_MANAGEMENT_TEMPLATE_ACCESS", "Dostęp do tego jest ustawiony jako"); 	

	define("USERS_MANAGEMENT_TEMPLATE_EDIT", "Edytuj");

    define("USERS_MANAGEMENT_TEMPLATE_PREVIEW", "Podgląd");

	define("USERS_MANAGEMENT_TEMPLATE_PROPERTIES", "Właściwości");				

	define("USERS_MANAGEMENT_TEMPLATE_GIVE", "Daj ten szablon innemu użytkownikowi");

	define("USERS_MANAGEMENT_TEMPLATE_GIVE_BUTTON", "Daj szablon");

	define("USERS_MANAGEMENT_TEMPLATE_NONE", "Ten użytkownik nie ma obecnie żadnych szablonów");

    define("USERS_MANAGEMENT_TEMPLATE_OWNER", "Właściciel");

    define("USERS_MANAGEMENT_TEMPLATE_ROLE", "Rola");
?>