<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("USERS_TOGGLE", "Pokaż");

	define("USERS_ID", "Nr użytkownika to ");

	define("USERS_FIRST", "Imię użytkownika to ");

	define("USERS_KNOWN", "Nazwisko użytkownika to ");
	
	define("USERS_USERNAME", "Nazwa użytkownika to");

    define("USERS_MANAGE_AUTH", "Autoryzowani użytkownicy");

    define("USERS_MANAGE_ACTIVE", "Aktywni użytkownicy z Obiektami Nauczania");
	
?>