<?PHP     
	
	/**
	 * 
	 * export template template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("EXPORT_TITLE","Export");

	define("EXPORT_DESCRIPTION","There are four ways to export a project");
	
	define("EXPORT_ZIP","A zip file export will package (but not delete) your project into one zip file. If you then open this file, the contents can be used to deploy your project on any webpage.</p><p>Click on zip export to get your file - ");
	
	define("EXPORT_ZIP_LINK","Zip export");
		
	define("EXPORT_ZIP_LOCAL","As above, but with references to web based files altered - ");
	
	define("EXPORT_ZIP_LOCAL_LINK","Zip (local) export");
	
	define("EXPORT_SCORM","A SCORM 1.2 file export will package (but not delete) your project into one zip file. This zip file can then be imported by most VLEs to become part of an online course. This file will be SCORM 1.2 compliant.</p><p>Click on Scorm export to get this package - ");
	
	define("EXPORT_SCORM_LINK","Scorm export");
		
	define("EXPORT_SCORM_METADATA","As above, but with richer SCORM metadata - ");
	
	define("EXPORT_SCORM_METADATA_LINK","SCORM + metadata export");

	define("EXPORT_FAIL","Sorry you do not have rights to this template");

?>

	