<?PHP

	/**
	 *
	 * export template template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("EXPORT_TITLE","Export");
	
	define("EXPORT_ERROR","You do not have rights to this project");
	
	define("EXPORT_FAIL","Only the creator and co-authors of the project can export this project");
	
	define("EXPORT_NOT_AVAILABLE","Export is not available for this template");


