<?PHP     

	/**
	 * 
	 * Gift template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	// XML SHARING TAB

	define("GIFT_INSTRUCTIONS", "To give this project to someone, please type their name here. The user must have an account on the site to appear in this search.");

	define("GIFT_NAMES", "Names will appear here");
		
	define("GIFT_FAIL", "You have no rights to this project");

?>