<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
	 
	// XML SHARING TAB

	define("GIFT_INSTRUCTIONS", "To give a copy of this project to another person, type their name below. Users must have an account on the site to appear in this search.");
	
	define("GIFT_SEARCH_LABEL", "Recipient of project");

	define("GIFT_NAMES", "Names will appear here");
		
	define("GIFT_ERROR", "You do not have rights to this project");
	
	define("GIFT_FAIL", "Only the creator and co-authors of the project can give this project to another person");

