<?PHP     

	/**
	 * 
	 * Gift template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	// XML SHARING TAB

	define("GIFT_RESPONSE_FAIL", "Sorry you no longer have rights to this template");
	
	define("GIFT_RESPONSE_SUCCESS", "Project successfully gifted to");
			
	define("GIFT_RESPONSE_INSTRUCTIONS","To give this project to someone, please type their name here");
			
	define("GIFT_RESPONSE_NAMES","Names will appear here");

?>