<?PHP     

	/**
	 * 
	 * Gift template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	// XML SHARING TAB

	define("GIFT_INSTRUCTIONS", "To give a copy of this project to another person, type their name below. Users must have an account on the site to appear in this search.");
	
	define("GIFT_SEARCH_LABEL", "Recipient of project");

	define("GIFT_NAMES", "Names will appear here");
		
	define("GIFT_ERROR", "You do not have rights to this project");
	
	define("GIFT_FAIL", "Only the creator and co-authors of the project can give this project to another person");

