<?PHP     

	/**
	 * 
	 * sharing status template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("SHARING_INSTRUCTION","To share this project with a group, select a group below.");

	define("SHARING_CURRENT","This project is currently shared with the following groups: ");

    define("SHARING_CREATOR", "Creator");

    define("SHARING_COAUTHOR", "Co-author");

    define("SHARING_EDITOR","Editor");

	define("SHARING_READONLY","Read only");

    define("SHARING_REMOVE_DESCRIPTION", "Press the button below to remove any sharing rights");

    define("SHARING_REMOVE", "Remove");

	define("SHARING_STOP","Click to stop sharing this project");

	define("SHARING_NOT_SHARED","This project is not shared with any group");

	define("SHARING_FAIL","You have no rights to this project");

	define("SHARING_ADD","Share with group");

?>