<?PHP 

	/**
	 * 
	 * media and quota template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	// XML SHARING TAB

	define("MEDIA_AND_QUOTA_USE", "In use");

	define("MEDIA_AND_QUOTA_IMPORT_MEDIA", "Import media");

	define("MEDIA_AND_QUOTA_CLICK_FILENAME", "Click on a file name and a link will appear below");

	define("MEDIA_AND_QUOTA_BUTTON_IMPORT", "Import");

	define("MEDIA_AND_QUOTA_DOWNLOAD", "Download this file");
	
	define("MEDIA_AND_QUOTA_NOT_IN_USE", "Not in use");
	
	define("MEDIA_AND_QUOTA_DELETE", "Click to delete");
	
	define("MEDIA_AND_QUOTA_USAGE", "This project is currently using");

	define("MEDIA_AND_QUOTA_UPLOAD", "Upload");

	define("MEDIA_AND_QUOTA_LINK", "Click on a file name and a link will appear below");
	
	define("MEDIA_AND_QUOTA_PUBLISH", "In use / Not in use refer to whether the file is used in the published version, not the working version");
	
	define("MEDIA_AND_QUOTA_FAIL", "Sorry you do not have rights to this project");

?>