<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
	 
	// XML SHARING TAB
	
	define("MEDIA_AND_QUOTA_USAGE", "This project is currently");

	define("MEDIA_AND_QUOTA_IMPORT_MEDIA", "Click the 'Choose File' button to select a new file to upload to the project.");
	
	define("MEDIA_AND_QUOTA_BUTTON_IMPORT", "Import");

	define("MEDIA_AND_QUOTA_CLICK_FILENAME", "All media and other files within your project are listed below. Click a file name to view a direct link to the file and have the option to download a copy.");
	
	define("MEDIA_AND_QUOTA_DOWNLOAD", "Download");
	
	define("MEDIA_AND_QUOTA_PUBLISH", "'In use' refers to whether the file is directly linked to or displayed in your project. If you are using code libraries and/or indirectly linked files then those files may be labelled incorrectly below as not in use. Keep this in mind when deleting.");
	
	define("MEDIA_AND_QUOTA_FILE_NAME", "File name");
	
	define("MEDIA_AND_QUOTA_FILE_SIZE", "Size");
	
	define("MEDIA_AND_QUOTA_FILE_USED", "In use?");
	
	define("MEDIA_AND_QUOTA_USE", "In use");
	
	define("MEDIA_AND_QUOTA_NOT_IN_USE", "Not in use");
	
	define("MEDIA_AND_QUOTA_DELETE", "Click to delete");

    define("MEDIA_AND_QUOTA_UNUSED_DELETE", "Delete all unused files");
	
	define("MEDIA_AND_QUOTA_FAIL", "You do not have rights to this project");

