<?PHP

	/**
	 *
	 * properties_library english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

    define("PROPERTIES_LIBRARY_SAVE", "Save");

    define("PROPERTIES_LIBRARY_RENAME", "Rename");

	// XML SHARING TAB

	define("PROPERTIES_LIBRARY_XML_TITLE", "XML sharing");

	define("PROPERTIES_LIBRARY_XML_DESCRIPTION", "You can turn on XML sharing for this project to allow your work to be used in other systems. The project must be published for this to work.");

	define("PROPERTIES_LIBRARY_XML_SHARING", "Allow XML sharing");

	define("PROPERTIES_LIBRARY_ON", "on");

	define("PROPERTIES_LIBRARY_OFF", "off");

	define("PROPERTIES_LIBRARY_XML_RESTRICT", "To restrict access to one site, enter the site's URL below");

	define("PROPERTIES_LIBRARY_XML_SAVE", "Your changes have been saved");

    define("PROPERTIES_LIBRARY_XML_LINK", "The link for xml sharing is ");

    define("PROPERTIES_LIBRARY_XML_ERROR", "Only the creator and co-authors of the project can set up XML sharing");

	//PROJECT INFO PANEL IN THE WORKSPACE - MORE TERSE TEXT
	define ("PROJECT_INFO_NAME", "Name");

	define ("PROJECT_INFO_ID", "ID");

	define ("PROJECT_INFO_CREATED", "Created on");

	define ("PROJECT_INFO_MODIFIED", "Last modified on");

	define ("PROJECT_INFO_FRAMEWORK", "Template");

	define ("PROJECT_INFO_RUNTIME", "Player");

	define ("PROJECT_INFO_URL", "URL");

	define ("PROJECT_INFO_EMBEDCODE", "Embed Code");

	define ("PROJECT_STATISTICS_UNAVAILABLE", "xAPI tracking data is unavailable");

	define ("PROJECT_INFO_MEDIA", "Project size");

	define ("PROJECT_INFO_ACCESS", "Access");

	define ("PROJECT_INFO_SHARED", "Shared");

    define ("PROJECT_INFO_PUBLISHED", "Published");

    define ("PROJECT_INFO_NOTPUBLISHED", "Not Published");

	define ("PROJECT_INFO_NOTSHARED", "Not shared");

    define("PROJECT_INFO_OAI", "Harvesting status");

	define ("PROJECT_INFO_PRIVATE", "Private");

	define ("PROJECT_INFO_PUBLIC", "Public");

	define ("PROJECT_INFO_PASSWORD", "Require login");

    define ("PROJECT_INFO_PASSWORD_PLAY", "Password protected");

	define ("PROJECT_INFO_OTHER", "Other");

	define ("PROJECT_INFO_ACCESS_SET_AS", "is currently set as");

	define ("PROJECT_INFO_NRVIEWS", ", number of views is %n");
	
	define ("PROJECT_INFO_NRVIEWSTITLE", "Views");

	define ("PROJECT_INFO_RSS_SYNDICATION" , "RSS: Project is published through rss");

	define ("PROJECT_INFO_RSS_SYNDICATION_RSSENABLED" , "RSS is enabled");

	define ("PROJECT_INFO_RSS_SYNDICATION_EXPORTENABLED" , "Export is enabled");

	define ("PROJECT_INFO_RSS_SYNDICATION_SYNDICATIONENABLED" , "Syndication is enabled");

	define("PROJECT_INFO_LTI_PUBLISHED" , "LTI: The project is published as an LTI 1.1 tool");

	define("PROJECT_INFO_XAPI_PUBLISHED", "xAPI: xAPI is enabled for this project through the following link:");

	define("GROUP_INFO_NAME", "Name");

	define("GROUP_INFO_MEMBERS", "Members");

// PROJECT TAB

	define("PROPERTIES_LIBRARY_PROJECT", "Project information");

	define("PROPERTIES_LIBRARY_PROJECT_NAME", "Project name");

	define("PROPERTIES_LIBRARY_PROJECT_CHANGED", "Name changed");

	define("PROPERTIES_LIBRARY_PROJECT_CREATE", "Created:");

	define("PROPERTIES_LIBRARY_PROJECT_MODIFY", "Last modified:");

    define("PROPERTIES_LIBRARY_DEFAULT_ENGINE", "Default interface:");
	
	define("PROPERTIES_LIBRARY_DEFAULT_ENGINE_WARNING", "Please note that Flash is no longer supported and this should only be used to convert older Flash projects to use the HTML5 interface.");

    define("PROPERTIES_LIBRARY_PUBLISH_ENGINE", "Default engine");

    define("PROPERTIES_LIBRARY_DEFAULT_HTML5", "HTML5");

    define("PROPERTIES_LIBRARY_DEFAULT_FLASH", "Flash");
	
    define("PROPERTIES_LIBRARY_FLASH_WARNING", "The Flash player is no longer supported. You can change the default player to HTML5 in the project properties");

    define("PROPERTIES_LIBRARY_DEFAULT_ENGINE_CHANGED", "Default interface has been changed.");

	define("PROPERTIES_LIBRARY_PROJECT_LINK", "The link to allow other people to access this project is:");

	define("PROPERTIES_LIBRARY_PROJECT_HTML5_LINK", "To allow other people to access the HTML 5 version, the link is");

	define("PROPERTIES_LIBRARY_PROJECT_IFRAME", "This code will allow you to embed your project into a web page");

	define("PROPERTIES_LIBRARY_PROJECT_FAIL", "You do not have rights to this project");
	
	define("PROPERTIES_LIBRARY_PROJECT_LINKS", " (opens in new window)");


	// NOTES TAB

	define("PROPERTIES_LIBRARY_NOTES", "Project Notes:");

	define("PROPERTIES_LIBRARY_NOTES_EXPLAINED", "These notes are only visible to the creator and any co-authors of the project");

	define("PROPERTIES_LIBRARY_NOTES_SAVED", "Notes saved");

	define("PROPERTIES_LIBRARY_NOTES_FAIL", "Only the creator and co-authors of the project can add notes");


	// PEER TAB

	define("PROPERTIES_LIBRARY_PEER", "Peer review");

	define("PROPERTIES_LIBRARY_PEER_EXPLAINED", "Set up peer review to create a password protected link to share. The peer review link allows people to view the project, alongside a form to complete with comments that can be emailed back to you.<br>Note: it is a good idea to check the peer review works as expected by sending yourself a test review before sending the peer review link to others.");

	define("PROPERTIES_LIBRARY_PEER_STATUS", "Peer review");

    define("PROPERTIES_LIBRARY_PEER_LINK", "The link for peer review is");
    
    define("PROPERTIES_LIBRARY_PEER_PASSWORD_PROMPT", "Password to give to reviewers");

    define("PROPERTIES_LIBRARY_PEER_RETOUREMAIL_PROMPT", "E-mail addresses for feedback (comma separated list)");

	define("PROPERTIES_LIBRARY_PEER_SAVED", "Peer review settings changed");

	define("PROPERTIES_LIBRARY_PEER_FAIL", "Only the creator and co-authors of the project can set up peer review");
	
	define("PROPERTIES_LIBRARY_PEER_LINKS", " (opens in new window)");


	// SYNDICATION TAB

	define("PROPERTIES_LIBRARY_SYNDICATION", "Open content");

	define("PROPERTIES_LIBRARY_SYNDICATION_EXPLAINED", "You can include this content in the site's open courseware list. Open Courseware is a set of learning materials that institutions have made publically available for any one to use. The address for this site's syndicated content is");

	define("PROPERTIES_LIBRARY_SYNDICATION_PROMPT", "Include this project in the Open Courseware Feed");

	define("PROPERTIES_LIBRARY_YES", "Yes");

	define("PROPERTIES_LIBRARY_NO", "No");

	define("PROPERTIES_LIBRARY_SYNDICATION_CATEGORY", "Project category");

	define("PROPERTIES_LIBRARY_SYNDICATION_LICENCE", "Project licence");

	define("PROPERTIES_LIBRARY_SYNDICATION_DESCRIPTION", "Project description");

	define("PROPERTIES_LIBRARY_SYNDICATION_KEYWORDS", "Project keywords (comma separated list)");

	define("PROPERTIES_LIBRARY_SYNDICATION_SAVED", "Your changes have been saved");

	define("PROPERTIES_LIBRARY_SYNDICATION_PUBLIC", "Set this project to 'Public' on the access tab before using the Syndication feature");

	define("PROPERTIES_LIBRARY_SYNDICATION_URL", "The address for this site's syndicated content is");

	define("PROPERTIES_LIBRARY_SYNDICATION_FAIL", "Only the creator and co-authors of the project can set syndication");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_LINKS", " (opens in new window)");




	// ACCESS TAB

	define("PROPERTIES_LIBRARY_ACCESS", "This project is currently set as");

	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC", "Public");

	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC_EXPLAINED", "The project will be visible to anyone on the internet");

	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD", "Require login");

	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD_EXPLAINED", "The project will be visible to people with an account on this system");

	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD_PLAY", "Password protected");

	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD_PLAY_EXPLAINED", "The project will be visible to people using the following password:");

	define("PROPERTIES_LIBRARY_ACCESS_OTHER", "Other");

	define("PROPERTIES_LIBRARY_ACCESS_OTHER_EXPLAINED", "Using this setting restricts access to your content. Your content will only be visible to people following links to your content from the sites you provide. Enter the site URLs below, separating individual URLs with commas.");

	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE", "Private");

	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE_EXPLAINED", "This makes your project visible to editors only.");

	define("PROPERTIES_LIBRARY_ACCESS_FAIL", "Only the creator and co-authors of the project can change the access settings");

	define("PROPERTIES_LIBRARY_ACCESS_BUTTON_CHANGE", "Change Access");

    define("PROPERTIES_LIBRARY_ACCESS_CHANGED", "The new access settings are saved.");

	// RSS TAB

	define("PROPERTIES_LIBRARY_RSS", "RSS feeds");

	define("PROPERTIES_LIBRARY_RSS_INCLUDE", "Include this project in the RSS Feeds");

	define("PROPERTIES_LIBRARY_RSS_DESCRIPTION", "Project description");

	define("PROPERTIES_LIBRARY_RSS_SITE", "You can include this content in the site's RSS feeds. People who subscribe to the feeds will see new content as it as added to the feeds. There are several feeds available.");
	
	define("PROPERTIES_LIBRARY_RSS_FEEDS","Available feeds");

	define("PROPERTIES_LIBRARY_RSS_SITE_LINK", "Main feed");
	
	define("PROPERTIES_LIBRARY_RSS_SITE_DESCRIPTION", "This includes all content marked for inclusion from the site's users.");

	define("PROPERTIES_LIBRARY_RSS_PERSONAL", "Your own RSS Feed");

	define("PROPERTIES_LIBRARY_RSS_MINE", "This only includes the content you have marked for inclusion.");

	define("PROPERTIES_LIBRARY_RSS_FOLDER", "Folder feeds");

	define("PROPERTIES_LIBRARY_RSS_FOLDER_DESCRIPTION", "As you organise content in folders, each folder has it's own RSS feed. This provides a convenient way to include only some of your content in a feed. See the folder properties for more details, and the link to that folder's feed.");

	define("PROPERTIES_LIBRARY_RSS_EXPORT", "Include this project in the export feed");
	
	define("PROPERTIES_LIBRARY_RSS_EXPORT_DESCRIPTION", "This will allow other users to download your project and make changes to it themselves");

	define("PROPERTIES_LIBRARY_RSS_SAVED", "Your changes have been saved");

	define("PROPERTIES_LIBRARY_RSS_PUBLIC", "Set this project to 'Public' on the access tab before using the RSS Feed features");

	define("PROPERTIES_LIBRARY_RSS_FAIL", "Only the creator and co-authors of the project can edit RSS settings");
	
	define("PROPERTIES_LIBRARY_RSS_LINKS", " (opens in new window)");

	// LTI/xAPI TAB

	define("PROPERTIES_LIBRARY_TSUGI_FAIL", "Only the creator and co-authors of the project can set LTI/xAPI properties");

	define("PROPERTIES_LIBRARY_TSUGI", "LTI/xAPI");

	define("PROPERTIES_LIBRARY_TSUGI_DESCRIPTION", "<p>Here you can publish your project as an LTI1.1 or LTI1.3 tool. To add the project as an LTI1.3 tool, an LTI1.3 issuer needs to be configured in the TSUGI admin panel. To add this project via LTI1.1 to a learning environment the auto generated key, secret and URL specific to this project will need to be added to the learning environment. You can change the auto populated values but remember the key must be unique for this project in this Xerte installation.</p><p>You can also choose to track activities through xAPI. To do this you need to specify the end-point, the username and the password of the LRS that is going to receive the xAPI events. You can use xAPI without Tsugi/LTI installed but in this case the only option you have as a learner identifier is setting a group value. The group will need to be specified in the launch URL (substitute groupname by the groupname you want to be used).</p>");

	define("PROPERTIES_LIBRARY_TSUGI_NOTAVAILABLE_DESCRIPTION", "<p>You can publish your project as an LTI1.1 or LTI1.3 tool if you install and configure TSUGI as part of your installation. <strong>TSUGI is not currently installed.</strong> See <a href='https://xot.xerte.org.uk/play.php?template_id=88' target='_blank'>how to install TSUGI guide</a> (opens in new window) for further details.</p><p>You can also choose to track activities through xAPI. To do this you need to specify the end-point, the username and the password of the LRS that is going to receive the xAPI events. You can use xAPI without Tsugi/LTI installed but in this case the only option you have as a learner identifier is setting a group value. The group will need to be specified in the launch URL (substitute groupname by the groupname you want to be used).</p>");

	define("PROPERTIES_LIBRARY_TSUGI_PUBLISH", "Publish project through Tsugi as an LTI tool");

    define("PROPERTIES_LIBRARY_TSUGI_USEGLOBAL", "Use globally configured keys and secrets (including LTI 1.3) ");

    define("PROPERTIES_LIBRARY_TSUGI_PUBLISH_IN_STORE", "Show in the TSUGI (LTI) deeplink store ");

    define("PROPERTIES_LIBRARY_TSUGI_PUBLISH_DASHBOARD_IN_STORE", "Show dashboard in the TSUGI (LTI) deeplink store ");

    define("PROPERTIES_LIBRARY_TSUGI_USEPRIVATEONLY", "Allow only private key/secret configured below ");

	define("PROPERTIES_LIBRARY_TSUGI_NAME", "Name:");

    define("PROPERTIES_LIBRARY_TSUGI_KEY", "LTI 1.1 Key:");

	define("PROPERTIES_LIBRARY_TSUGI_SECRET", "LTI 1.1 Secret:");

	define("PROPERTIES_LIBRARY_TSUGI_ENABLE_XAPI", "Enable xAPI");

    define("PROPERTIES_LIBRARY_TSUGI_DASHBOARD_URLS", "Dashboard urls (separated by commas)");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_USEGLOBAL", "Use globally configured xAPI LRS");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_ENDPOINT", "xAPI LRS end-point:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_USERNAME", "xAPI LRS username:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_PASSWORD", "xAPI LRS password/secret:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE", "xAPI LRS learner id mode:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_0", "e-mail address");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_1", "hashed e-mail address");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_2", "full name and e-mail address");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_3", "group");

	define("PROPERTIES_LIBRARY_TSUGI_UPDATE_BUTTON_LABEL", "Update");
	
	define("PROPERTIES_LIBRARY_TSUGI_UPDATED", "LTI1 / xAPI details changed");

	define("PROPERTIES_LIBRARY_TSUGI_LTI_LAUNCH_URL", "LTI 1.1 launch URL:");

    define("PROPERTIES_LIBRARY_TSUGI_LTI13_LAUNCH_URL", "LTI 1.3 launch URL:");



