<?PHP

	/**
	 * 
	 * properties_library english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

    define("PROPERTIES_LIBRARY_SAVE", "Save");

    define("PROPERTIES_LIBRARY_RENAME", "Rename");

	// XML SHARING TAB

	define("PROPERTIES_LIBRARY_XML_TITLE", "XML Sharing");
	
	define("PROPERTIES_LIBRARY_XML_DESCRIPTION", "In this section you can set up the XML Sharing for one of your projects. Your project must be published for this to work. This allows your work to be used in other systems");
	
	define("PROPERTIES_LIBRARY_XML_SHARING", "XML Sharing is");
	
	define("PROPERTIES_LIBRARY_ON", "on");
	
	define("PROPERTIES_LIBRARY_OFF", "off");
			
	define("PROPERTIES_LIBRARY_XML_RESTRICT", "You can restrict access to one site if you would like");
	
	define("PROPERTIES_LIBRARY_XML_SAVE", "Your changes have been saved");
	
	define("PROPERTIES_LIBRARY_XML_ERROR", "Sorry, only creators of templates can set up XML sharing");
	
	
	// PROJECT TAB
	
	define("PROPERTIES_LIBRARY_PROJECT", "Project");
	
	define("PROPERTIES_LIBRARY_PROJECT_NAME", "Project name");
	
	define("PROPERTIES_LIBRARY_PROJECT_CHANGED", "Name changed");
	
	define("PROPERTIES_LIBRARY_PROJECT_CREATE", "This file was created on");
	
	define("PROPERTIES_LIBRARY_PROJECT_MODIFY", "This file was last modified on");
	
	define("PROPERTIES_LIBRARY_PROJECT_LINK", "To allow other people to access this file, the link is");
	
	define("PROPERTIES_LIBRARY_PROJECT_HTML5_LINK", "To allow other people to access the HTML 5 version, the link is");
	
	define("PROPERTIES_LIBRARY_PROJECT_IFRAME", "This code will allow you to embed your project into a web page");
			
	define("PROPERTIES_LIBRARY_PROJECT_FAIL", "Sorry you do not have rights to this template");
	
	
	// NOTES TAB
	
	define("PROPERTIES_LIBRARY_NOTES", "Project Notes:");
	
	define("PROPERTIES_LIBRARY_NOTES_EXPLAINED", "These notes are only visible to yourself");
	
	define("PROPERTIES_LIBRARY_NOTES_SAVED", "Notes saved");
	
	define("PROPERTIES_LIBRARY_NOTES_FAIL", "Sorry only the creator of the file can set notes for the project");
	
	
	// PEER TAB
	
	define("PROPERTIES_LIBRARY_PEER", "Peer review");
	
	define("PROPERTIES_LIBRARY_PEER_EXPLAINED", "In this section you can set up the peer review for one of your projects. This allows you to send a password protected link to staff, allowing them to access a project, and then giving them the facility to email you feedback");
		
	define("PROPERTIES_LIBRARY_PEER_STATUS", "Peer review is");

    define("PROPERTIES_LIBRARY_PEER_LINK", "The link for peer review is ");

    define("PROPERTIES_LIBRARY_PEER_PASSWORD_PROMPT", "Password to give to reviewers ");

    define("PROPERTIES_LIBRARY_PEER_RETOUREMAIL_PROMPT", "E-mail addresses (seperated by ',') to send feedback to ");

	define("PROPERTIES_LIBRARY_PEER_SAVED", "Peer review settings changed");
			
	define("PROPERTIES_LIBRARY_PEER_FAIL", "Sorry, only creators of templates can set up peer review");
	
	
	// SYNDICATION TAB
	
	define("PROPERTIES_LIBRARY_SYNDICATION", "Open Content");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_EXPLAINED", "This tab allows you to include to project in the site's open courseware list. Open Courseware is a set of learning materials that institutions have made publically available for any one to use. The address for this site's syndicated content is");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_PROMPT", "Include this project in the Open Courseware Feed");	

	define("PROPERTIES_LIBRARY_YES", "Yes");

	define("PROPERTIES_LIBRARY_NO", "No");

	define("PROPERTIES_LIBRARY_SYNDICATION_CATEGORY", "Please choose a category for your project");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_LICENCE", "Please choose a licence for your project");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_DESCRIPTION", "Please provide a description for your project");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_KEYWORDS", "Please provide a list of comma separated keywords for this project");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_SAVED", "Your changes have been saved");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_PUBLIC", "Please set this project to the 'Public' on the access tab before using the Syndication feature");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_URL", "The address for this site's syndicated content is");

	define("PROPERTIES_LIBRARY_SYNDICATION_FAIL", "Sorry only the creator of the file can set syndication for the project");
	
	
	
	
	// ACCESS TAB
	
	define("PROPERTIES_LIBRARY_ACCESS", "This file is currently set as"); 

	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC", "Public");

	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC_EXPLAINED", "The template will be visible to anyone on the internet");
		
	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD", "Password protected");
		
	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD_EXPLAINED", "The template will be visible to people with an account on this system");
		
	define("PROPERTIES_LIBRARY_ACCESS_OTHER", "Other");
		
	define("PROPERTIES_LIBRARY_ACCESS_OTHER_EXPLAINED", "Using this setting restricts access to your content. Your content will only be visible to people following links to your content from the site you provide. Enter the site URL below.");
		
	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE", "Private");
		
	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE_EXPLAINED", "This makes your template visible to editors only.");
		
	define("PROPERTIES_LIBRARY_ACCESS_FAIL", "Sorry only the creator can set the access settings");
	
	define("PROPERTIES_LIBRARY_ACCESS_BUTTON_CHANGE", "Change Access");

    define("PROPERTIES_LIBRARY_ACCESS_CHANGED", "The new access settings are saved.");

	// RSS TAB
	
	define("PROPERTIES_LIBRARY_RSS", "RSS feeds");
	
	define("PROPERTIES_LIBRARY_RSS_INCLUDE", "Include this project in the RSS Feeds"); 
	
	define("PROPERTIES_LIBRARY_RSS_DESCRIPTION", "You can also include a description for your project in the RSS Feed as well");
	
	define("PROPERTIES_LIBRARY_RSS_SITE", "You can include this content in the site's RSS feeds. People who subscribe to the feeds will see new content as it as added to the feeds. There are several feeds available");

	define("PROPERTIES_LIBRARY_RSS_SITE_LINK", "The main feed is at");
	
	define("PROPERTIES_LIBRARY_RSS_PERSONAL", "This includes all content marked for inclusion from the site's users. <Br><Br> Your own RSS Feed is available at"); 
	
	define("PROPERTIES_LIBRARY_RSS_MINE", "This only includes the content you have marked for inclusion.");

	define("PROPERTIES_LIBRARY_RSS_FOLDER", "As you organise content in folders, each folder has it's own RSS feed. This provides a convenient way to include only some of your content in a feed. See the folder properties for more details, and the link to that folder's feed");

	define("PROPERTIES_LIBRARY_RSS_EXPORT", "Including content in the export feed allows other users to download your project and make changes to it themselves");

	define("PROPERTIES_LIBRARY_RSS_SAVED", "Your changes have been saved");
	
	define("PROPERTIES_LIBRARY_RSS_PUBLIC", "Please set this project to the 'Public' on the access tab before using the RSS Feed features");
	
	define("PROPERTIES_LIBRARY_RSS_FAIL", "Sorry only the creator of the file can set notes for the project");

	
?>
	
