<?PHP

	/**
	 *
	 * properties_library english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

    define("PROPERTIES_LIBRARY_SAVE", "Save");

    define("PROPERTIES_LIBRARY_RENAME", "Rename");

	// XML SHARING TAB

	define("PROPERTIES_LIBRARY_XML_TITLE", "XML Sharing");

	define("PROPERTIES_LIBRARY_XML_DESCRIPTION", "In this section you can set up the XML Sharing for one of your projects. Your project must be published for this to work. This allows your work to be used in other systems");

	define("PROPERTIES_LIBRARY_XML_SHARING", "XML Sharing is");

	define("PROPERTIES_LIBRARY_ON", "on");

	define("PROPERTIES_LIBRARY_OFF", "off");

	define("PROPERTIES_LIBRARY_XML_RESTRICT", "You can restrict access to one site if you would like");

	define("PROPERTIES_LIBRARY_XML_SAVE", "Your changes have been saved");

	define("PROPERTIES_LIBRARY_XML_ERROR", "Sorry, only creators or co-authors of projects can set up XML sharing");

	//PROJECT INFO PANEL IN THE WORKSPACE - MORE TERSE TEXT
	define ("PROJECT_INFO_NAME", "Name");

	define ("PROJECT_INFO_ID", "Id");

	define ("PROJECT_INFO_CREATED", "Created on");

	define ("PROJECT_INFO_MODIFIED", "Last modified on");

	define ("PROJECT_INFO_RUNTIME", "Player");

	define ("PROJECT_INFO_URL", "URL");

	define ("PROJECT_INFO_EMBEDCODE", "Embed Code");

	define ("PROJECT_STATISTICS_UNAVAILABLE", "xAPI tracking data is unavailable");

	define ("PROJECT_INFO_MEDIA", "Project size");

	define ("PROJECT_INFO_ACCESS", "Access");

	define ("PROJECT_INFO_SHARED", "Shared");

	define ("PROJECT_INFO_NOTSHARED", "Not Shared");

	define ("PROJECT_INFO_PRIVATE", "Private");

	define ("PROJECT_INFO_PUBLIC", "Public");

	define ("PROJECT_INFO_PASSWORD", "Password");

	define ("PROJECT_INFO_OTHER", "Other");

	define ("PROJECT_INFO_ACCESS_SET_AS", "is currently set as");

	define ("PROJECT_INFO_NRVIEWS", ", number of views is %n");

	define ("PROJECT_INFO_RSS_SYNDICATION" , "RSS: Project is published through rss");

	define ("PROJECT_INFO_RSS_SYNDICATION_RSSENABLED" , "RSS is enabled");

	define ("PROJECT_INFO_RSS_SYNDICATION_EXPORTENABLED" , "Export is enabled");

	define ("PROJECT_INFO_RSS_SYNDICATION_SYNDICATIONENABLED" , "Syndication is enabled");

	define("PROJECT_INFO_LTI_PUBLISHED" , "LTI: The project is published as an LTI 1.1 tool");

	define("PROJECT_INFO_XAPI_PUBLISHED", "xAPI: xAPI is enabled for this project through the following link:");

// PROJECT TAB

	define("PROPERTIES_LIBRARY_PROJECT", "Project");

	define("PROPERTIES_LIBRARY_PROJECT_NAME", "Project name");

	define("PROPERTIES_LIBRARY_PROJECT_CHANGED", "Name changed");

	define("PROPERTIES_LIBRARY_PROJECT_CREATE", "This project was created on");

	define("PROPERTIES_LIBRARY_PROJECT_MODIFY", "This project was last modified on");

    define("PROPERTIES_LIBRARY_DEFAULT_ENGINE", "What is the default engine to use for this project?");

    define("PROPERTIES_LIBRARY_PUBLISH_ENGINE", "Default engine");

    define("PROPERTIES_LIBRARY_DEFAULT_HTML5", "HTML5");

    define("PROPERTIES_LIBRARY_DEFAULT_FLASH", "Flash");

    define("PROPERTIES_LIBRARY_DEFAULT_ENGINE_CHANGED", "Default engine has been changed.");

	define("PROPERTIES_LIBRARY_PROJECT_LINK", "To allow other people to access this project, the link is");

	define("PROPERTIES_LIBRARY_PROJECT_HTML5_LINK", "To allow other people to access the HTML 5 version, the link is");

	define("PROPERTIES_LIBRARY_PROJECT_IFRAME", "This code will allow you to embed your project into a web page");

	define("PROPERTIES_LIBRARY_PROJECT_FAIL", "Sorry you do not have rights to this project");


	// NOTES TAB

	define("PROPERTIES_LIBRARY_NOTES", "Project Notes:");

	define("PROPERTIES_LIBRARY_NOTES_EXPLAINED", "These notes are only visible to yourself");

	define("PROPERTIES_LIBRARY_NOTES_SAVED", "Notes saved");

	define("PROPERTIES_LIBRARY_NOTES_FAIL", "Sorry only the creator or co-authors of the project can set notes for the project");


	// PEER TAB

	define("PROPERTIES_LIBRARY_PEER", "Peer review");

	define("PROPERTIES_LIBRARY_PEER_EXPLAINED", "In this section you can set up the peer review for one of your projects. This allows you to send a password protected link to colleagues or learners, allowing them to access a project, and then giving them the facility to email you feedback. <br>Note: please check that this works by sending yourself a test review before sending the peer review link to others.");

	define("PROPERTIES_LIBRARY_PEER_STATUS", "Peer review is");

    define("PROPERTIES_LIBRARY_PEER_LINK", "The link for peer review is ");

    define("PROPERTIES_LIBRARY_PEER_PASSWORD_PROMPT", "Password to give to reviewers ");

    define("PROPERTIES_LIBRARY_PEER_RETOUREMAIL_PROMPT", "E-mail addresses (seperated by ',') to send feedback to ");

	define("PROPERTIES_LIBRARY_PEER_SAVED", "Peer review settings changed");

	define("PROPERTIES_LIBRARY_PEER_FAIL", "Sorry, only creators or co-authors of projects can set up peer review");


	// SYNDICATION TAB

	define("PROPERTIES_LIBRARY_SYNDICATION", "Open Content");

	define("PROPERTIES_LIBRARY_SYNDICATION_EXPLAINED", "This tab allows you to include to project in the site's open courseware list. Open Courseware is a set of learning materials that institutions have made publically available for any one to use. The address for this site's syndicated content is");

	define("PROPERTIES_LIBRARY_SYNDICATION_PROMPT", "Include this project in the Open Courseware Feed");

	define("PROPERTIES_LIBRARY_YES", "Yes");

	define("PROPERTIES_LIBRARY_NO", "No");

	define("PROPERTIES_LIBRARY_SYNDICATION_CATEGORY", "Please choose a category for your project");

	define("PROPERTIES_LIBRARY_SYNDICATION_LICENCE", "Please choose a licence for your project");

	define("PROPERTIES_LIBRARY_SYNDICATION_DESCRIPTION", "Please provide a description for your project");

	define("PROPERTIES_LIBRARY_SYNDICATION_KEYWORDS", "Please provide a list of comma separated keywords for this project");

	define("PROPERTIES_LIBRARY_SYNDICATION_SAVED", "Your changes have been saved");

	define("PROPERTIES_LIBRARY_SYNDICATION_PUBLIC", "Please set this project to the 'Public' on the access tab before using the Syndication feature");

	define("PROPERTIES_LIBRARY_SYNDICATION_URL", "The address for this site's syndicated content is");

	define("PROPERTIES_LIBRARY_SYNDICATION_FAIL", "Sorry only the creator or co-author of the project can set syndication for the project");




	// ACCESS TAB

	define("PROPERTIES_LIBRARY_ACCESS", "This project is currently set as");

	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC", "Public");

	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC_EXPLAINED", "The project will be visible to anyone on the internet");

	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD", "Password protected");

	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD_EXPLAINED", "The project will be visible to people with an account on this system");

	define("PROPERTIES_LIBRARY_ACCESS_OTHER", "Other");

	define("PROPERTIES_LIBRARY_ACCESS_OTHER_EXPLAINED", "Using this setting restricts access to your content. Your content will only be visible to people following links to your content from the sites you provide. Enter the site URLs below, separating individual URLs with commas.");

	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE", "Private");

	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE_EXPLAINED", "This makes your project visible to editors only.");

	define("PROPERTIES_LIBRARY_ACCESS_FAIL", "Sorry only the creator or co-author can set the access settings");

	define("PROPERTIES_LIBRARY_ACCESS_BUTTON_CHANGE", "Change Access");

    define("PROPERTIES_LIBRARY_ACCESS_CHANGED", "The new access settings are saved.");

	// RSS TAB

	define("PROPERTIES_LIBRARY_RSS", "RSS feeds");

	define("PROPERTIES_LIBRARY_RSS_INCLUDE", "Include this project in the RSS Feeds");

	define("PROPERTIES_LIBRARY_RSS_DESCRIPTION", "Please add a useful description for your project in the box below and press the Save button.");

	define("PROPERTIES_LIBRARY_RSS_SITE", "You can include this content in the site's RSS feeds. People who subscribe to the feeds will see new content as it as added to the feeds. There are several feeds available");

	define("PROPERTIES_LIBRARY_RSS_SITE_LINK", "The main feed is at");

	define("PROPERTIES_LIBRARY_RSS_PERSONAL", "This includes all content marked for inclusion from the site's users. <Br><Br> Your own RSS Feed is available at");

	define("PROPERTIES_LIBRARY_RSS_MINE", "This only includes the content you have marked for inclusion.");

	define("PROPERTIES_LIBRARY_RSS_FOLDER", "As you organise content in folders, each folder has it's own RSS feed. This provides a convenient way to include only some of your content in a feed. See the folder properties for more details, and the link to that folder's feed");

	define("PROPERTIES_LIBRARY_RSS_EXPORT", "Including content in the export feed allows other users to download your project and make changes to it themselves");

	define("PROPERTIES_LIBRARY_RSS_SAVED", "Your changes have been saved");

	define("PROPERTIES_LIBRARY_RSS_PUBLIC", "Please set this project to the 'Public' on the access tab before using the RSS Feed features");

	define("PROPERTIES_LIBRARY_RSS_FAIL", "Sorry only the creator or co-author of the project can set notes for the project");

	// LTI/xAPI TAB

	define("PROPERTIES_LIBRARY_TSUGI_FAIL", "Sorry only the creator or co-author of the project can set LTI/xAPI properties for the project");

	define("PROPERTIES_LIBRARY_TSUGI", "LTI/xAPI");

	define("PROPERTIES_LIBRARY_TSUGI_DESCRIPTION", "<p>Here you can publish your project as an LTI1 tool. To add this project via LTI to a learning environment the auto generated key, secret and URL specific to this project will need to be added to the learning environment. You can change the auto populated values but remember the key must be unique for this project in this Xerte installation. If you are enabling others to add this project via LTI to their learning environment they will need each of these details too.</p><p>You can also choose to track activities through xAPI. If you want to do that you need to specify the end-point, the username and the password of the LRS that is going to receive the xAPI events. If you want to track activities without LTI, the only option you have as a learner identifier is setting a group value. The group will need to be specified in the launch URL (substitute groupname by the groupname you want to used).</p>");

	define("PROPERTIES_LIBRARY_TSUGI_NOTAVAILABLE_DESCRIPTION", "<p>Here you could publish your project as an LTI1 tool if you install and configure TSUGI as part of your installation, however Tsugi is not currently installed. See <a href='https://xot.xerte.org.uk/play.php?template_id=88' target='_blank'>how to install Tsugi</a> for further details.</p><p>You can also choose to track activities through xAPI. If you want to do so you need to specify the end-point, the username and the password of the LRS that is going to receive the xAPI events. You can still use xAPI without Tsugi/LTI installed but in this case the only option you have as a learner identifier is setting a group value. The group will need to be specified in the launch URL (substitute groupname by the groupname you want to be used).</p>");

	define("PROPERTIES_LIBRARY_TSUGI_PUBLISH", "Publish project through Tsugi as an LTI1 tool");

	define("PROPERTIES_LIBRARY_TSUGI_NAME", "Name:");

    define("PROPERTIES_LIBRARY_TSUGI_KEY", "Key:");

	define("PROPERTIES_LIBRARY_TSUGI_SECRET", "Secret:");

	define("PROPERTIES_LIBRARY_TSUGI_ENABLE_XAPI", "Enable xAPI:");

    define("PROPERTIES_LIBRARY_TSUGI_DASHBOARD_URLS", "Dashboard urls (separated by commas)");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_USEGLOBAL", "Use globally configured xAPI LRS:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_ENDPOINT", "xAPI LRS end-point:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_USERNAME", "xAPI LRS username:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_PASSWORD", "xAPI LRS password/secret:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE", "xAPI LRS learner id mode:");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_0", "e-mail address");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_1", "hashed e-mail address");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_2", "full name and e-mail address");

	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_3", "group");

	define("PROPERTIES_LIBRARY_TSUGI_UPDATE_BUTTON_LABEL", "Update");

	define("PROPERTIES_LIBRARY_TSUGI_LTI_LAUNCH_URL", "Your launch url is:");


?>

