<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("PUBLISH_TITLE","Project");

	define("PUBLISH_DESCRIPTION","This window contains all the settings you need to publish your project.");

	define("PUBLISH_NAME","Project name");

	define("PUBLISH_ACCESS","Access");
	
	define("PUBLISH_ACCESS_DESCRIPTION","If you have not published this project before, you must select the appropriate option in the 'Access' tab. This controls how your users can access your content. To set the access options, select the 'Access' tab and follow the instructions");
	
	define("PUBLISH_ACCESS_STATUS","As your project is private, publishing alone will not make your content available for others to view. Select the 'Access' tab to change the project's access setting before continuing.");
	
	define("PUBLISH_ACCESS_IS","Your project is currently set as");
	
	define("PUBLISH_RSS","RSS");
	
	define("PUBLISH_RSS_DESCRIPTION","RSS feeds provide a convenient way for your users to keep up to date with your content. To include this project in your Xerte RSS feeds, select the 'RSS' tab.");
	
	define("PUBLISH_RSS_NOT_INCLUDE","This project is not in any RSS feeds");
	
	define("PUBLISH_RSS_INCLUDE","This project is available in the RSS Feeds");
	
	define("PUBLISH_SYNDICATION","Open Content");
	
	define("PUBLISH_SYNDICATION_DESCRIPTION","Syndicating your content makes it available to the widest possible audience by allowing it to be harvested by open-access repositories of content. To syndicate your project, select the 'Open Content' tab.");
	
	define("PUBLISH_SYNDICATION_STATUS_OFF","This project is not currently syndicated.");
	
	define("PUBLISH_SYNDICATION_STATUS_ON","This project is currently syndicated");

    define ("PUBLISH_BUTTON_LABEL", "Publish");

    define("PUBLISH_WEB_ADDRESS","URL");
	
	define("PUBLISH_FAIL","You do not have rights to this project");
	
	define("PUBLISH_LINKS", " (opens in new window)");
	
