<?PHP     

	/**
	 * 
	 * publish english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("PUBLISH_TITLE","Project");

	define("PUBLISH_DESCRIPTION","This panel contains all the settings you need to publish your project.");

	define("PUBLISH_ACCESS","Access");
	
	define("PUBLISH_ACCESS_DESCRIPTION","If you have not published this project before, you must select the appropriate option in the 'Access' tab. This controls how your users can access your content. To set the access options, select the 'Access' tab and follow the instructions");
	
	define("PUBLISH_ACCESS_STATUS","Your project is currently private. Click on 'Access' to change this");
	
	define("PUBLISH_ACCESS_IS","Your project is currently set as");
	
	define("PUBLISH_RSS","RSS");
	
	define("PUBLISH_RSS_DESCRIPTION","RSS feeds provide a convenient way for your users to keep up to date with your content. If you'd like to add this project to your RSS feeds, select the 'RSS' tab and follow the instructions");
	
	define("PUBLISH_RSS_NOT_INCLUDE","Your project is not in any RSS feeds");
	
	define("PUBLISH_RSS_INCLUDE","Your project is available in the RSS Feeds");
	
	define("PUBLISH_SYNDICATION","Syndication");
	
	define("PUBLISH_SYNDICATION_DESCRIPTION","Syndicating your content makes it available to the widest possible audience by making it available for harvesting by open-access repositories of content. To syndicate your project, select the 'Syndication' tab and follow the instructions");
	
	define("PUBLISH_SYNDICATION_STATUS_OFF","Your project is not currently syndicated.");
	
	define("PUBLISH_SYNDICATION_STATUS_ON","Your project is currently syndicated");

    define ("PUBLISH_BUTTON_LABEL", "Publish");

    define("PUBLISH_WEB_ADDRESS","The web address for this resource is");
	
	define("PUBLISH_FAIL","Sorry you do not have rights to this project");
	
?>