<?PHP     

	/**
	 * 
	 * sharing status template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("SHARING_INSTRUCTION","To share this template with some one, please type their name here. The user must have an account on the site to appear in this search.");
	
	define("SHARING_NAMES","Names will appear here");

	define("SHARING_CURRENT","This template is currently shared with : ");

    define("SHARING_CREATOR", "Creator");

	define("SHARING_EDITOR","Editor");

	define("SHARING_READONLY","Read only");

    define("SHARING_REMOVE_DESCRIPTION", "Press the button below to remove any sharing rights");

    define("SHARING_REMOVE", "Remove");

	define("SHARING_STOP","Click to stop sharing this file");

	define("SHARING_NOT_SHARED","This template is not shared");

	define("SHARING_FAIL","You have no rights to this template");

?>