<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("SHARING_INSTRUCTION","To share this project with another person/group, type their name below. Users must have an account on the site to appear in this search.");
	
	define("SHARING_NAME_LABEL", "Recipient of project");
	
	define("SHARING_ROLE_LABEL", "Role");
	
	define("SHARING_NAMES","Names will appear here");

	define("SHARING_CURRENT","This project is currently shared with: ");

    define("SHARING_CURRENT_FOLDER","This folder is currently shared with: ");

    define("SHARING_CREATOR", "Creator");

    define("SHARING_COAUTHOR", "Co-author");

    define("SHARING_EDITOR","Editor");

	define("SHARING_READONLY","Read only");

    define("SHARING_SOURCE","from ");

    define("SHARING_SOURCE_FOLDER","folder");

    define("SHARING_SOURCE_TEMPLATE","project");

    define("SHARING_REMOVE_DESCRIPTION", "Press the button below to remove any sharing rights");

    define("SHARING_REMOVE", "Remove");

	define("SHARING_STOP_INSTRUCTIONS","If you no longer need access to this project, you can stop it being shared with you:");
	
	define("SHARING_STOP","Remove sharing");

	define("SHARING_NOT_SHARED","This project is not currently shared");

	define("SHARING_FAIL","You do not have rights to this project");

