<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("TEMPLATE_CLOSE_FILE","Dostępny plik");

	define("TEMPLATE_CLOSE_EMAIL_GREETINGS","Witaj,"); 

	define("TEMPLATE_CLOSE_EMAIL_INTRODUCTION"," Zażądałeś bycia poinformowanym kiedy plik");

	define("TEMPLATE_CLOSE_EMAIL_MESSAGE"," będzie dostępny do edycji. Plik stał się dostępny");
 
	define("TEMPLATE_CLOSE_EMAIL_MESSAGE_MORE"," Proszę zauważyć, że może być stworzonych wiele żądań, i tak jak ty nie możesz być jedyną osobą do otrzymania jednego z tych powiadomień. Jako taki plik może dobrze być jeszcze blokowany przez kogoś innego.");

	define("TEMPLATE_CLOSE_EMAIL_LOG_IN"," Proszę zalogować się na stronie");
 
	define("TEMPLATE_CLOSE_EMAIL_CLOSING_SUBJECT"," Dziękuję, ");
 
	define("TEMPLATE_CLOSE_EMAIL_SIGNATURE"," Zespół Narzędzi Xerte Online");

	define("TEMPLATE_CLOSE_QUESTION","Chcesz opublikować swoje zmiany?");


?>