<?PHP

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

    define("XERTE_EXPORT_HTML5", "Eksportuj z silnikiem JavaScript (tj. HTML5)");
    define("XERTE_EXPORT_FLASH", "Eksportuj z silnikiem Flash");
	define("XERTE_EXPORT_DESCRIPTION","Jest tutaj kilka dróg do eksportu projektu. Eksportowany projekt jest spakowany, ale nie usuwany, plik zip może być dzielony z innym użytkownikiem, umieścić na stronie, lub zaimportować jako SCORM do platformy LMS lub VLE. Możesz wybrać czy chcesz eksportować wszystkie pliki projektów, lub te pliki używane przez projekt.");

  define("XERTE_EXPORT_ZIP_ARCHIVE", "Eksport archiwum. Kompletna kopia zapasowa zawierająca niedostępną edycję i powrotną konwersję do narzędzi lub dzielenia się z innymi użytkownikami Xerte: ");
  define("XERTE_EXPORT_ZIP_ARCHIVE_LINK","Pobierz archiwum ZIP.");

  define("XERTE_EXPORT_ZIP", "Eksport dla wdrożenia. Zawiera tylko pliki wymagane do importu z VLE bez śledzenia SCORM, dzielenia przez CD lub USB, itd. lub importowania z innej instalacji XOT: ");
	define("XERTE_EXPORT_ZIP_LINK","Pobierz wdrożeniowy ZIP.");

	define("XERTE_EXPORT_SCORM", "Eksportuje dla wdrożenia SCORM: sam zawiera, SCORM 1.2 lub SCORM 2004 włączając śledzenie wyników quizu, np. dla dziennika ocen Moodle: ");

	define("XERTE_EXPORT_SCORM_12_LINK","Pobierz pakiet SCORM 1.2");

	define("XERTE_EXPORT_SCORM_2004_LINK","Pobierz pakiet SCORM 2004");

?>

