<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("XERTE_PEER_DESCRIPTION", "Strona wzajemnej weryfikacji");
	
	define("XERTE_PEER_GUIDANCE", "Proszę zweryfikować ten obiekt nauczania. Użyj poniższego formularza odpowiedzi aby wysłać własną wypowiedź.");
	
	define("XERTE_PEER_TEXTAREA_INSTRUCTIONS", "Zostałeś poproszony o dostarczenie jakieś odpowiedzi dla tego obiektu nauczania. Proszę wprowadzić swoją odpowiedź i kliknąć na zapisz kiedy zakończysz. Odpowiedź jest anonimowa.");

    define("XERTE_PEER_BUTTON_SEND", "Wyślij");

    define("XERTE_PEER_PASSWORD", "Hasło");

    define("XERTE_PEER_LOGIN_BUTTON", "Zaloguj się");

?>