<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("TEMPLATE_CLOSE_FILE","File available");

	define("TEMPLATE_CLOSE_EMAIL_GREETINGS","Hello,"); 

	define("TEMPLATE_CLOSE_EMAIL_INTRODUCTION","You've requested to be informed when the project");

	define("TEMPLATE_CLOSE_EMAIL_MESSAGE"," becomes available for editing. The project was made available at");
 
	define("TEMPLATE_CLOSE_EMAIL_MESSAGE_MORE"," Please note that multiple requests may have been made, and as such you may not be the only person to have receive one of these notifications. As such the project may well be locked by somebody else.");

	define("TEMPLATE_CLOSE_EMAIL_LOG_IN"," Please log into the site at");
 
	define("TEMPLATE_CLOSE_EMAIL_CLOSING_SUBJECT"," Thank you, ");
 
	define("TEMPLATE_CLOSE_EMAIL_SIGNATURE"," the Xerte Online toolkits team");

	define("TEMPLATE_CLOSE_QUESTION","Would you like to publish your changes?");


