<?PHP     

	/**
	 * 
	 * template close language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("TEMPLATE_CLOSE_FILE","File available");

	define("TEMPLATE_CLOSE_EMAIL_GREETINGS","Hello,"); 

	define("TEMPLATE_CLOSE_EMAIL_INTRODUCTION","You've requested to be informed when the project");

	define("TEMPLATE_CLOSE_EMAIL_MESSAGE"," becomes available for editing. The project was made available at");
 
	define("TEMPLATE_CLOSE_EMAIL_MESSAGE_MORE"," Please note that multiple requests may have been made, and as such you may not be the only person to have receive one of these notifications. As such the project may well be locked by somebody else.");

	define("TEMPLATE_CLOSE_EMAIL_LOG_IN"," Please log into the site at");
 
	define("TEMPLATE_CLOSE_EMAIL_CLOSING_SUBJECT"," Thank you, ");
 
	define("TEMPLATE_CLOSE_EMAIL_SIGNATURE"," the Xerte Online toolkits team");

	define("TEMPLATE_CLOSE_QUESTION","Would you like to publish your changes?");


?>