<?PHP   

	/**
	 * 
	 * feedback/index.htm english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("FEEDBACK_TITLE","Welcome to Xerte Online Toolkits");
	define("FEEDBACK_RESPONSE","Thank you for your feedback");
	define("FEEDBACK_EMAIL_TITLE","Xerte Online Feedback");
	define("FEEDBACK_GIVER","Name ");
	define("FEEDBACK_MESSAGE_INTRO","Message");
	define("FEEDBACK_PAGE_TITLE","Welcome to Xerte on-line Toolkits Feedback page");
	define("FEEDBACK_DESCRIPTION","Please leave your feedback here. All feedback is anonymous, unless you would like a response, and if you do, please leave your name opposite and some contact details in the box below.");
	define("FEEDBACK_TEXTAREA","Feedback");
	define("FEEDBACK_BUTTON","Send Feedback");

?>