<?PHP  
/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 

	/**
	 * 
	 * feedback/index.htm english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("FEEDBACK_TITLE","Welcome to Xerte Online Toolkits");
	define("FEEDBACK_RESPONSE","Thank you for your feedback");
	define("FEEDBACK_EMAIL_TITLE","Xerte Online Feedback");
	define("FEEDBACK_GIVER","Name ");
	define("FEEDBACK_MESSAGE_INTRO","Message");
	define("FEEDBACK_PAGE_TITLE","Welcome to Xerte Online Toolkits Feedback page");
	define("FEEDBACK_DESCRIPTION","Please leave your feedback here. All feedback is anonymous, unless you would like a response, and if you do, please leave your name opposite and some contact details in the box below.");
	define("FEEDBACK_TEXTAREA","Feedback");
	define("FEEDBACK_BUTTON","Send Feedback");

?>