<?php

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


define("IMAGEUPOLOAD_NOT_UPLOADED", "Something went wrong while trying to uplod file!");
define("IMAGEUPLOAD_INVALID_FORMAT", "Invalid image format: has to be an png, jpg or gif image!");
define("IMAGEUPLOAD_RENAMED", "The file has been renamed from {0} to {1}");
define("IMAGEUPLOAD_TOO_LARGE", "The file has is to larger ({0} bytes) then allowed ({1} bytes)");
define("IMAGEUPLOAD_ERROR", "There was an error uploading the image file: ");
define("IMAGEUPLOAD_FORM_SIZE", "The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form.");
define("IMAGEUPLOAD_PARTIAL_FILE", "The uploaded file was only partially uploaded.");
define("IMAGEUPLOAD_NO_FILE", "No file was uploaded.");
define("IMAGEUPLOAD_NO_TMP_DIR", "Missing a temporary folder.");
define("IMAGEUPLOAD_CANT_WRITE", "Failed to write file to disk.");
define("IMAGEUPLOAD_EXTENSION", "File upload stopped by extension.");

