<?PHP     

	/**
	 * 
	 * Simile Edit english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("SIMILE_EDIT_TITLE", "Simile Editor Window");
	
	define("SIMILE_DESC_TEXT", "Enter the description for your timeline here. You can use &lt;p&gt;, &lt;img&gt; and &lt;a&gt; HTML tags.");
	
	define("SIMILE_START_STOP", "Timeline start and end years");
	
	define("SIMILE_START", "Start");
	
	define("SIMILE_STOP", "Stop");
	
	define("SIMILE_START_STOP_EXTRA" , "In these fields enter the years you want your timeline to start and stop.");
	
	define("SIMILE_ZONE", "Timeline zones");
	
	define("SIMILE_ZONE_EXPLAIN", "A zone is a band on the time zone reflecting a grouping of events");
	
	define("SIMILE_EXISTING_ZONES", "Existing zones");
	
	define("SIMILE_UNIT", "Unit");
	
	define("SIMILE_WIDTH", "Width");
	
	define("SIMILE_HOUR", "Hour");
	
	define("SIMILE_DAY", "Day");
	
	define("SIMILE_MONTH", "Month");
	
	define("SIMILE_YEAR", "Year");
	
	define("SIMILE_DECADE", "Decade");
	
	define("SIMILE_CENTURY", "Century");
	
	define("SIMILE_ZONE_GUIDE", "Which Time Zones should this zone sync with? (Make sure each zone is only linked to once.) ");
	
	define("SIMILE_ZONE_SYNC", "Select a zone to sync");
	
	define("SIMILE_REMOVE", "Remove");
	
	define("SIMILE_NEW_ZONE", "Add a new zone");
	
	define("SIMILE_DATE_FORMAT", "Format the dates like this - so 1159 AM (GMT) on June 1st 2012 is <b>2012-06-01T11:59:00+0000</b>");
	
	define("SIMILE_DATE_FORMAT_2", "So 2012 is the year, 06 is the month and 01 is the day - this is the minimum you must enter for each date.");
	
	define("SIMILE_DATE_FORMAT_3", "11:59:00 is the time (minutes are supported, and +0000 means GMT. ");
	
	define("SIMILE_WIDTH_EXPLAIN", "By default use '100%' but again, you might wish to experiment with this.");
	
	define("SIMILE_UNIT_EXPLAIN", "This is the unit shown on the timeline for this zone. Hours will show hours, days with show days, and so on.");
	
	define("SIMILE_UNIT_SIZE", "Size of each unit");
	
	define("SIMILE_ZONE_UNIT_EXPLAIN", "You must add a size for the zone to be added. Experiment with this size if you want different time zones to use different scales");
	
	define("SIMILE_ZONE_LABELS", "Timeline zone labels");
	
	define("SIMILE_ZONE_LABEL_INSTRUCTION", "Add a text label for a zone");
	
	define("SIMILE_ZONE_LABEL_CHOICE", "A label for which zone");
	
	define("SIMILE_ZONE_NEW_LABEL", "Add new event label");
	
	define("SIMILE_ZONE_FORMAT", "Start date and end dates should use the same format as specified above");
	
	define("SIMILE_ZONE_START_DATE", "Start Date");
	
	define("SIMILE_ZONE_END_DATE", "End Date");
	
	define("SIMILE_ZONE_START_LABEL", "Start Label");
	
	define("SIMILE_ZONE_END_LABEL", "End Label");
	
	define("SIMILE_ZONE_APPEAR", "Which Time Zone should this event appear in?");
	
	define("SIMILE_COLOUR", "Colour");
	
	define("SIMILE_OPACITY", "Opacity");
	
	define("SIMILE_HEXA", "The hexadecimal colour code. You can see");
	
	define("SIMILE_HEXA_LINK", "http://en.wikipedia.org/wiki/Web_colors");
	
	define("SIMILE_HEXA_EXAMPLES", "some example colours if you would like help");
	
	define("SIMILE_OPACITY_EXPLAINED", "Expressed as a percentage of 100 (no percent symbol needed).");
	
	define("SIMILE_TIMELINE_EVENTS","Timeline events");
	
	define("SIMILE_EXISTING_EVENTS", "Existing events");
	
	define("SIMILE_ZONE_APPEAR_EVENT","Which Time Zones should this event appear in?");
	define("SIMILE_ZONE_ZONE", "Zone"); 
	define("SIMILE_EVENT_TITLE", "Title (This is the text that will appear omn the timeline)");
	define("SIMILE_EVENT_DESCRIPTION", "Description (This is text which appears in the bubble when the timeline is clicked on)");
	define("SIMILE_EVENT_LINK", "Link (Web address to make available in the bubble)");
	define("SIMILE_EVENT_IMAGE", "Image (Web address of picture used in the bubble)");
	define("SIMILE_EVENT_START", "Start (date of event, or date when event starts - please see date format mentioned above)");
	define("SIMILE_EVENT_LATEST_START", "Latest start");
	define("SIMILE_EVENT_EARLIEST_END", "Earliest end");
	define("SIMILE_EVENT_END", "End");
	define("SIMILE_EVENT_DURATION_EVENT", "Duration Event (if you want the event to be a line between two dates - start and end - check this box ). ");
	define("SIMILE_TEXT_COLOUR", "Text Colour");
	define("SIMILE_PREVIEW", "Preview");

?>