<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
	 
	define("XERTE_EXPORT_DESCRIPTION", "Exported projects are downloaded to your computer in a zip file. The original project is not deleted and will remain in Xerte. There are several ways to export a project.");
	
    define("XERTE_EXPORT_INTERFACE", "Export interface:");
    define("XERTE_EXPORT_HTML5", "HTML5");
    define("XERTE_EXPORT_FLASH", "Flash (please note that Flash is no longer supported)");
	
	define("XERTE_EXPORT_ZIP_TITLE", "Deployment export");
	define("XERTE_EXPORT_ZIP", "Contains only the files required for importing into a VLE/LMS (without SCORM tracking), deploying onto a web server, or for importing into another Xerte installation.");
	define("XERTE_EXPORT_ZIP_LINK","Get deployment zip");
	
	define("XERTE_EXPORT_ZIP_ARCHIVE_TITLE", "Archive export");
    define("XERTE_EXPORT_ZIP_ARCHIVE", "Complete export only really needed for troubleshooting xml or other issues.");
    define("XERTE_EXPORT_ZIP_ARCHIVE_LINK","Get archive zip");