<?PHP

	/**
	 *
	 * export page template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

    define("XERTE_EXPORT_HTML5", "Export with Javascript (a.k.a. HTML5) Engine");
    define("XERTE_EXPORT_FLASH", "Export with Flash Engine");
	define("XERTE_EXPORT_DESCRIPTION","There are several ways to export a project. An exported project is packaged, but not deleted, into a zip file for you to share with another user, to deploy on the web, or to import into a SCORM compliant LMS or VLE. You can choose whether to export all of the project's files, or just those files used by the project.");

  define("XERTE_EXPORT_ZIP_ARCHIVE", "Archive export. Complete backup including offline editing and round-tripping back to toolkits or sharing with other Xerte users: ");
  define("XERTE_EXPORT_ZIP_ARCHIVE_LINK","Get Archive Zip.");

  define("XERTE_EXPORT_ZIP", "Export for deployment. Contains only the files required for importing into a vle without SCORM tracking, sharing via CD or USB etc or importing into another XOT install: ");
	define("XERTE_EXPORT_ZIP_LINK","Get Deployment Zip.");

	define("XERTE_EXPORT_SCORM", "Export for SCORM deployment: self contained, SCORM 1.2 or SCORM 2004 enables tracking of Quiz scores e.g. into Moodle gradebook: ");

	define("XERTE_EXPORT_SCORM_12_LINK","Get SCORM 1.2 package");

	define("XERTE_EXPORT_SCORM_2004_LINK","Get SCORM 2004 3rd Ed package");

?>

