<?PHP

/**
 *
 * automation/index page template language file
 *
 * @author Patrick Lockley
 * @version 1.0
 * @copyright Pat Lockley
 * @package
 */

define("AUTOMATION_DO_SHARE_SUCCESS_MESG", "<p>Action is successfully completed for:</p><p><ul><li>%on learning objects (%ocr created, %oup updated, %oun untouched)</li><li>%sn student shared objects (%scr created, %sup updated, %sun untouched)</li><li>%tn teacher shared objects (%tcr created, %tup updated, %tun untouched)</li></ul></p>");

define("AUTOMATION_DO_SHARE_FAILED", "Empty action, group, template or readonly parameter");
