<?PHP

/**
 *
 * automation/index page template language file
 *
 * @author Patrick Lockley
 * @version 1.0
 * @copyright Pat Lockley
 * @package
 */

define("AUTOMATION_INTRO", "<h2>Duplicate and share projects with groups of students.</h2><p>Please carefully select the template to use as a master and the group to share with.</p>");

define("AUTOMATION_LABEL_TEACHER", "Teacher:");

define("AUTOMATION_LABEL_COURSE", "Course:");

define("AUTOMATION_LABEL_GROUP", "Group:");

define("AUTOMATION_LABEL_TEMPLATE", "Template:");

define("AUTOMATION_LABEL_READONLY", "Readonly");

define("AUTOMATION_LABEL_UNSHARE_TEACHERS", "Unshare (other) teachers as well");

define("AUTOMATION_LABEL_PRACTICE", "Practice");

define("AUTOMATION_LABEL_ATTEMPT", "Attempt ");

define("AUTOMATION_BUTTON_SHARE", "Share now");

define("AUTOMATION_BUTTON_UNSHARE", "Unshare now");

define("AUTOMATION_ACCESS_DENIED_OR_NO_COURSES", "<h2>Access denied</h2><p>You do not have permission to use this automation page.</p>");

define("AUTOMATION_BUTTON_GOTO_WORKSPACE", "Go back to Xerte Workspace");

define("AUTOMATION_BUTTON_GOTO_OWNERSHIP", "Change ownership");
