<?PHP

/**
 *
 * automation/index page template language file
 *
 * @author Patrick Lockley
 * @version 1.0
 * @copyright Pat Lockley
 * @package
 */

define("AUTOMATION_OWNERSHIP_INTRO", "<h2>Transfer ownership of shared templates to another teacher</h2><p>Please select the template that needs to be transferred and choose the new owner.</p>");

define("AUTOMATION_LABEL_TEACHER", "Teacher:");

define("AUTOMATION_LABEL_COURSE", "Course:");

define("AUTOMATION_LABEL_GROUP", "Group:");

define("AUTOMATION_LABEL_TEMPLATE", "Template:");

define("AUTOMATION_ACCESS_DENIED_OR_NO_COURSES", "<h2>Access denied</h2><p>You do not have permission to use this automation page.</p>");

define("AUTOMATION_BUTTON_GOTO_WORKSPACE", "Go back to Xerte Workspace");

define("AUTOMATION_BUTTON_GOTO_SHARING", "Go back to sharing");

define("AUTOMATION_LABEL_SHARED_TEMPLATES", "All the shared templates of this group");

define("AUTOMATION_LABEL_NEW_OWNER", "Select the new owner");

define("AUTOMATION_BUTTON_CHANGE_OWNER", "Change ownership");
