<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("PEER_REVIEW_FEEDBACK","Odpowiedź zwrotna w projekcie");
	
	define("PEER_REVIEW_EMAIL_GREETING","Witaj,");
	
	define("PEER_REVIEW_EMAIL_INTRO","Otrzymałeś zwrotną odpowiedź w swoich projekcie.");
	
	define("PEER_REVIEW_EMAIL_YOURS","Dziękujemy za użycie strony");
	
	define("PEER_REVIEW_EMAIL_SIGNATURE","Zespół Projektowy Xerte");

	define("PEER_REVIEW_USER_FEEDBACK","Twoja odpowiedź zwrotna została wysłana do użytkownika");
	
	define("PEER_REVIEW_PROBLEM","Wystąpił problem");
	
?>