<?PHP     

	/**
	 * 
	 * display_library.php english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("DISPLAY_RECYCLE", "Recycle Bin");

	define("DISPLAY_EXAMPLE", "See example");

	define("DISPLAY_CREATE", "Create");

    define("DISPLAY_BUTTON_PROJECT_CREATE", "Create Project");

    define("DISPLAY_NAME", "Enter a name for this project");
	
    define("DISPLAY_PROJECT_NAME", "Project name");

    define("DISPLAY_CHOOSE_AND_NAME", "Choose a predefined template then enter a name for this project");
	
	define("DISPLAY_TEMPLATE", "Template");

    define("DISPLAY_DEFAULT_TEMPLATE", "Default");
	
	define("DISPLAY_ERROR", "An error has occured and as such you cannot edit at present");
	
	define("DISPLAY_EDITED", "This project is currently locked as it is already being edited by ");

    define("DISPLAY_LOCKFILE_TIME", "The editing session began on ");
	
	define("DISPLAY_LOCKFILE_MESSAGE", "If you are sure that the project is no longer being edited (and the editor window is closed), then you can edit the project by clicking the button below. If you continue, and another editor is open for this project, there is a risk that you will lose work or that the project will become corrupted. Alternatively, please wait and you will be automatically emailed when the project is available for editing.");

	define("DISPLAY_LOCKFILE_YOU", "you");

	define("DISPLAY_LOCKFILE_YOU_MESSAGE", "If you are sure this is not the case and that you are no longer editing on another device or browser tab/window, then you can edit the project by clicking the button below. If you continue, and another editor is open for this project, there is a risk that you will lose work or that the project will become corrupted.");

	define("DISPLAY_LOCKFILE_DELETE", "Delete lockfile and continue to editor");

    define("DISPLAY_WORKSPACE","Workspace");
