<?PHP     

	/**
	 * 
	 * display_library.php english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("DISPLAY_RECYCLE", "Recycle Bin");

	define("DISPLAY_EXAMPLE", "See example");

	define("DISPLAY_CREATE", "Create");

    define("DISPLAY_BUTTON_PROJECT_CREATE", "Create Project");

    define("DISPLAY_NAME", "Enter a name for this project");

    define("DISPLAY_CHOOSE_AND_NAME", "Choose a predifined template then enter a name for this project");

    define("DISPLAY_DEFAULT_TEMPLATE", "Default");
	
	define("DISPLAY_ERROR", "An error has occured and as such you cannot edit at present");
	
	define("DISPLAY_EDITED", "This project is currently being edited by ");
	
	define("DISPLAY_LOCKFILE_MESSAGE", "If you are sure this is not the case, then you can edit the project by clicking the button below. If you continue, and there are two or more people editing at once, there is a risk that you will lose work or that the project will become corrupted. Otherwise, please wait and you will be automatically emailed when the current editor closes the project down.");

	define("DISPLAY_LOCKFILE_YOU", "you");

	define("DISPLAY_LOCKFILE_YOU_MESSAGE", "If you are sure this is not the case, then you can edit the project by clicking the button below. If you continue, and you are editing in another browser or another PC, there is a risk that you will lose work or that the project will become corrupted. Please verify you are not editing the file in another system.");

	define("DISPLAY_LOCKFILE_DELETE", "Delete Lockfile");

    define("DISPLAY_WORKSPACE","Workspace");
