<?PHP     

	/**
	 * 
	 * display_library.php english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("DISPLAY_RECYCLE", "Recycle Bin");
	
	define("DISPLAY_EXAMPLE", "See example");
	
	define("DISPLAY_CREATE", "Create");
	
	define("DISPLAY_NAME", "Enter a name for this project");
	
	define("DISPLAY_ERROR", "An error has occured and as such you cannot edit at present");
	
	define("DISPLAY_EDITED", "This file is currently being edited by ");
	
	define("DISPLAY_LOCKFILE_MESSAGE", "If you are sure this is not the case, then you can edit the file by clicking the button below. If you continue and there are two people editing at once, there is a risk the file will become corrupted. Otherwise, please wait until the current editor closes the file and it will be made available to you when the current editor closes it down.");
	
	define("DISPLAY_LOCKFILE_DELETE", "Delete Lockfile");


?>