<?PHP

	define("API_HEADER", "API");
	
	define("API_KEY", "Key");

	define("API_SECRET", "Secret");

	define("API_STATUS", "Status");

	define("API_CREATED", "Created on");

	define("API_MODIFIED", "Last modified on");

	define("API_NEVER_USED", "Has never been used.");

	define("API_LAST_USED", "Last used on");

	define("API_USED", "Has been used {x} times");

	define("API_NO_APPLICATIONS", "No applications registered.");

	define("API_NOT_INSTALLED", "API not yet installed.");
	
	define("API_ERROR", "You do not have rights to this workspace");