<?PHP    

	/**
	 * 
	 * Folder RSS Template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("FOLDER_RSS_TEMPLATE_MY", "My feeds");
	
	define("FOLDER_RSS_TEMPLATE_MY_FEED", "RSS feed");
	
	define("FOLDER_RSS_TEMPLATE_MY_FOLDER_FEED", "Folder RSS feeds");
	
	define("FOLDER_RSS_TEMPLATE_LINKS", " (opens in new window)");

	define("FOLDER_RSS_TEMPLATE_LINKS_NEW", "All links open in new window");
	
	define("FOLDER_RSS_TEMPLATE_ERROR", "You do not have rights to this workspace");
	
