<?PHP    

	/**
	 * 
	 * my properties (workspace) english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("MY_PROPERTIES_DETAILS", "My Details");
	
	define("MY_PROPERTIES_NAME_DETAILS", "My name on the system is");

	define("MY_PROPERTIES_LOGIN_DETAILS", "My last login was on");

	define("MY_PROPERTIES_USERNAME_DETAILS", "My username is");


?>