<?PHP    

	/**
	 * 
	 * my properties (workspace) english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("MY_PROPERTIES_DETAILS", "My details");
	
	define("MY_PROPERTIES_NAME_DETAILS", "Name");

	define("MY_PROPERTIES_LOGIN_DETAILS", "Last login");

	define("MY_PROPERTIES_USERNAME_DETAILS", "Username");
	
	define("MY_PROPERTIES_ERROR", "You do not have rights to this workspace");


