<?PHP     

	/**
	 * 
	 * peer (workspace) english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("PEER_REVIEW_INTRO", "Projects that you have created which have had peer review enabled are listed below. Click a link to open the project's peer review page in a new window:");

	define("PEER_REVIEW_NAME", "Peer review");
	
	define("PEER_REVIEW_PSWD", "Password");
	
	define("PEER_REVIEW_STATUS", "On");
	
	define("PEER_REVIEW_COPY", "Copy password to clipboard");
		
