<?PHP     

	/**
	 * 
	 * RSS (workspace) english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("RSS_WORKSPACE_INTRO", "Projects that you have created and included in the RSS feeds are listed below. Click a link to preview the project in a new window:");
	
	define("RSS_WORKSPACE_RSS", "RSS feed");
	
	define("RSS_WORKSPACE_EXPORT", "Export feed");
	
	define("RSS_WORKSPACE_OPEN", "Open courseware");
	
	define("RSS_WORKSPACE_OPEN_CATEGORY", "Category");

	define("RSS_WORKSPACE_ON", "On");
	
	define("RSS_WORKSPACE_OFF", "Off");
	
