<?PHP     
	
	/**
	 * 
	 * shared templates (workspace) english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("SHARED_TEMPLATE_INTRO", "All shared projects that you have access to are listed below. This includes projects that you have shared with others, as well as projects that other people have shared with you. Click a link to preview the project in a new window:");

	define("SHARED_TEMPLATE_CREATOR", "Creator");
	
