<?PHP     

	/**
	 * 
	 * syndication templates (workspace) english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("SYNDICATION_TEMPLATE_INTRO", "Projects you have included in the site's open courseware list are listed below. Click a link to preview the project in a new window:");
	
	define("SYNDICATION_TEMPLATE_TERM", "Syndication");

	define("SYNDICATION_TEMPLATE_ON", "On");
			
	define("SYNDICATION_TEMPLATE_OFF", "Off");
		
