<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("USAGE_TEMPLATE_INTRO", "The table below lists the number of times each project has been 'played'. This number is a simple count of how many times each project has been loaded - it does not look at unique user views or how much of each project has been viewed/completed. The list includes projects that you have created, as well as projects created by others which have been shared with you. Projects with no plays are not listed. Click a link to preview the project in a new window:");

	define("USAGE_TEMPLATE_STATS", "Plays");
	
