<?PHP     

	/**
	 * 
	 * shared templates (workspace) english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("USAGE_TEMPLATE_INTRO", "The table below lists the number of times each project has been 'played'. This number is a simple count of how many times each project has been loaded - it does not look at unique user views or how much of each project has been viewed/completed. The list includes projects that you have created, as well as projects created by others which have been shared with you. Projects with no plays are not listed. Click a link to preview the project in a new window:");

	define("USAGE_TEMPLATE_STATS", "Plays");
	
