<?PHP   

	/**
	 * 
	 * workspace library english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("WORKSPACE_LIBRARY_MY", "My projects");

	define("WORKSPACE_LIBRARY_SHARED", "Shared projects");
	
	define("WORKSPACE_LIBRARY_PUBLIC", "Public projects");
	
	define("WORKSPACE_LIBRARY_USAGE", "Usage stats");
	
	define("WORKSPACE_LIBRARY_RSS", "Projects in the RSS");
	
	define("WORKSPACE_LIBRARY_OPEN", "Open Content projects");
	
	define("WORKSPACE_LIBRARY_PEER", "Peer review");
	
	define("WORKSPACE_LIBRARY_XML", "XML sharing");

	define("WORKSPACE_LIBRARY_TEMPLATE_NAME", "Name");
		
?>