<?PHP   

	/**
	 * 
	 * workspace library english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("WORKSPACE_LIBRARY_MY", "My projects");

	define("WORKSPACE_LIBRARY_SHARED", "Shared projects");
	
	define("WORKSPACE_LIBRARY_PUBLIC", "Public projects");
	
	define("WORKSPACE_LIBRARY_USAGE", "Usage stats");
	
	define("WORKSPACE_LIBRARY_RSS", "RSS / Open content projects");
	
	define("WORKSPACE_LIBRARY_OPEN", "Open Content projects");
	
	define("WORKSPACE_LIBRARY_PEER", "Peer review");
	
	define("WORKSPACE_LIBRARY_XML", "XML sharing");

	define("WORKSPACE_LIBRARY_TEMPLATE_NAME", "Project name");
	
	define("WORKSPACE_LIBRARY_TEMPLATE_ID", "ID");
	
	define("WORKSPACE_LIBRARY_MY_PROJECTS_INTRO", "All projects that you have created are listed below. Click a link to preview the project in a new window:");
	
	define("WORKSPACE_LIBRARY_ACCESS", "Access");
	
	define("WORKSPACE_LIBRARY_PUBLIC_PROJECTS_INTRO", "All public projects that you have access to are listed below. This includes projects that you have created, as well as projects created by others which have been shared with you. Click a link to open the public facing URL for the project in a new window:");
	
	define("WORKSPACE_LIBRARY_LINK_WINDOW", "opens in new window");
	
	define("WORKSPACE_LIBRARY_ERROR", "You do not have rights to this workspace");
		
