<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("WORKSPACE_LIBRARY_MY", "My projects");

	define("WORKSPACE_LIBRARY_SHARED", "Shared projects");
	
	define("WORKSPACE_LIBRARY_PUBLIC", "Public projects");
	
	define("WORKSPACE_LIBRARY_USAGE", "Usage stats");
	
	define("WORKSPACE_LIBRARY_RSS", "RSS / Open content projects");
	
	define("WORKSPACE_LIBRARY_OPEN", "Open Content projects");
	
	define("WORKSPACE_LIBRARY_PEER", "Peer review");
	
	define("WORKSPACE_LIBRARY_XML", "XML sharing");

	define("WORKSPACE_LIBRARY_TEMPLATE_NAME", "Project name");
	
	define("WORKSPACE_LIBRARY_TEMPLATE_ID", "ID");
	
	define("WORKSPACE_LIBRARY_MY_PROJECTS_INTRO", "All projects that you have created are listed below. Click a link to preview the project in a new window:");
	
	define("WORKSPACE_LIBRARY_ACCESS", "Access");
	
	define("WORKSPACE_LIBRARY_PUBLIC_PROJECTS_INTRO", "All public projects that you have access to are listed below. This includes projects that you have created, as well as projects created by others which have been shared with you. Click a link to open the public facing URL for the project in a new window:");
	
	define("WORKSPACE_LIBRARY_LINK_WINDOW", "opens in new window");
	
	define("WORKSPACE_LIBRARY_ERROR", "You do not have rights to this workspace");
		
