<?PHP    
	
	/**
	 * 
	 * XML templates (workspace) english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("XML_TEMPLATE_INTRO", "Projects that you have created which have had XML sharing enabled are listed below. Click a link to preview the project in a new window:");
	
	define("XML_TEMPLATE_NAME", "XML sharing");
	
	define("XML_TEMPLATE_ON", "On");

	
