<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

define("USER_HAS_TEMPLATES_IN_FOLDER","The user you are about to remove the access of has projects in this folder (or sub-folders of this folder). If you remove access for this user, the projects will be moved to the root folder of the user and all other users will loose access to the projects. Do you want to continue?");

define("GROUP_HAS_TEMPLATES_IN_FOLDER","Some users of the group you are about to remove the access of have projects in this folder (or sub-folders of this folder). If you remove access for this group, these projects will be moved to the root folder of the creator of the project and all other users will loose access to the projects. Do you want to continue?");

define("YOU_HAVE_TEMPLATES_IN_FOLDER","You have projects in this folder (or sub-folders of this folder). If you remove your access your projects will be moved to your root folder and all other users will loose access to the projects. Do you want to continue?");

