<?PHP

/**
 *
 * sharing status folder template language file
 *
 * @author Patrick Lockley
 * @version 1.0
 * @copyright Pat Lockley
 * @package
 */

define("USER_HAS_TEMPLATES_IN_FOLDER","The user you are about to remove the access of has projects in this folder (or sub-folders of this folder). If you remove access for this user, the projects will be moved to the root folder of the user and all other users will loose access to the projects. Do you want to continue?");

define("GROUP_HAS_TEMPLATES_IN_FOLDER","Some users of the group you are about to remove the access of have projects in this folder (or sub-folders of this folder). If you remove access for this group, these projects will be moved to the root folder of the creator of the project and all other users will loose access to the projects. Do you want to continue?");

define("YOU_HAVE_TEMPLATES_IN_FOLDER","You have projects in this folder (or sub-folders of this folder). If you remove your access your projects will be moved to your root folder and all other users will loose access to the projects. Do you want to continue?");

