<?PHP     

	/**
	 * 
	 * folder properties template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("FOLDER_PROPERTIES_PROPERTIES","Folder properties");			

	define("FOLDER_PROPERTIES_CALLED","Folder name");
	
	define("FOLDER_PROPERTIES_CHANGE","Change the name of the folder");

    define("FOLDER_PROPERTIES_BUTTON_SAVE","Rename");
	
	define("FOLDER_PROPERTIES_CHANGED", "Name changed");

    define("FOLDER_PROPERTIES_FAIL","You do not have rights to this folder");
