<?PHP     

	/**
	 * 
	 * folder rss template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("FOLDER_RSS_FEEDS","Folder RSS feeds");
	
	define("FOLDER_RSS_PUBLIC","If there is any public content in this folder, you will be able to access it via the RSS Feed at");

    define("FOLDER_RSS_FAIL", "You do not have rights to this folder");
	
	define("FOLDER_RSS_LINKS", " (opens in new window)");
