<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("FOLDER_RSS_FEEDS","Folder RSS feeds");
	
	define("FOLDER_RSS_PUBLIC","If there is any public content in this folder, you will be able to access it via the RSS Feed at");

    define("FOLDER_RSS_FAIL", "You do not have rights to this folder");
	
	define("FOLDER_RSS_LINKS", " (opens in new window)");
