<?PHP     

	/**
	 * 
	 * sharing status folder template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("SHARING_INSTRUCTION","To share this folder with a user or a group, please type their name here. A user must have an account on the site to appear in this search. Also select a role to grant the user or group.");

	define("SHARING_NAMES","Names will appear here");

	define("SHARING_CURRENT","This folder is currently shared with : ");

    define("SHARING_CREATOR", "Creator");

    define("SHARING_COAUTHOR", "Co-author");

    define("SHARING_EDITOR","Editor");

	define("SHARING_READONLY","Read only");

    define("SHARING_REMOVE_DESCRIPTION", "Press the button below to remove any sharing rights");

    define("SHARING_REMOVE", "Remove");

    define("SHARING_STOP","Click to stop sharing this folder");

	define("SHARING_NOT_SHARED","This folder is not shared");

    define("SHARING_FAIL","You have no rights to this folder");

?>