<?PHP     

	/**
	 * 
	 * sharing status folder template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("SHARING_INSTRUCTION","To share this folder with another person/group, type their name below. Users must have an account on the site to appear in this search.");

	define("SHARING_NAME_LABEL", "Recipient of folder");
	
	define("SHARING_ROLE_LABEL", "Role");

	define("SHARING_NAMES","Names will appear here");

	define("SHARING_CURRENT","This folder is currently shared with:");

    define("SHARING_CREATOR", "Creator");

    define("SHARING_COAUTHOR", "Co-author");

    define("SHARING_EDITOR","Editor");

	define("SHARING_READONLY","Read only");

    define("SHARING_SOURCE","from ");

    define("SHARING_SOURCE_FOLDER","folder");

    define("SHARING_SOURCE_TEMPLATE","project");

    define("SHARING_REMOVE_DESCRIPTION", "Press the button below to remove any sharing rights");

    define("SHARING_REMOVE", "Remove");
	
	define("SHARING_STOP_INSTRUCTIONS","If you no longer need access to this folder, you can stop it being shared with you:");

    define("SHARING_STOP","Click to stop sharing this folder");

	define("SHARING_NOT_SHARED","This folder is not currently shared");

    define("SHARING_FAIL","You do not have rights to this folder");

    define("SHARING_FAIL_SHARED_SUBFOLDER","You cannot share a subfolder of a shared folder");


?>