<?PHP

	/**
	 * 
	 * file upload english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */	

	define("FILE_UPLOAD_ZIP_FAIL","File upload failed");

	define("FILE_UPLOAD_HTML_FAIL","File upload failed as that HTML contained PHP code");

	define("FILE_UPLOAD_SUCCESS","File successfully uploaded");

	define("FILE_UPLOAD_MIME_FAIL","Invalid file type");

?>