<?php

/**
 * 
 * import template english language file
 *
 * @author Patrick Lockley
 * @version 1.0
 * @copyright Pat Lockley
 * @package
 */
define("IMPORT_TEMPLATE_ZIP_FAIL", "Zip file not properly structured");

define("IMPORT_TEMPLATE_TEMPLATE_FAIL", "Template not setup correctly to work on toolkits");

define("IMPORT_TEMPLATE_RLT_FAIL", "No file called template.rlt found");

define("IMPORT_TEMPLATE_FOLDER_CREATE", "The folder has been created");

define("IMPORT_TEMPLATE_FOLDER_FAIL", "Error creating folder");

