<?PHP   
	
	/**
	 * 
	 * Import english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */	

	define("IMPORT_NAME_IF_EMPTY","Imported template");
	
	define("IMPORT_SUCCESS","New template imported");
	
	define("IMPORT_SUCCESS_REPLACE","Template successfully replaced");
	
	define("IMPORT_OWNER_FAIL","Only the owner of this template can import over the top");

	define("IMPORT_FTP_FAIL","File transfer has failed");

	define("IMPORT_TYPE_FAIL","Sorry, we cannot get a template type for this template");

	define("IMPORT_NO_EQUIVALENT_FAIL","No valid template equivalent found on this site. Please contact your system administrators.");

	define("IMPORT_ZIP_FAIL","You can only import Zip Files");
	
	define("IMPORT_XERTE_ONLY","Only Xerte templates are currently imported");


?>