<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("IMPORT_NAME_IF_EMPTY","Imported template");
	
	define("IMPORT_SUCCESS","New template imported");
	
	define("IMPORT_SUCCESS_REPLACE","Template successfully replaced");
	
	define("IMPORT_OWNER_FAIL","Only the owner of this template can import over the top");

	define("IMPORT_FTP_FAIL","File transfer has failed");

	define("IMPORT_TYPE_FAIL","Sorry, we cannot get a template type for this template");

	define("IMPORT_NO_EQUIVALENT_FAIL","No valid template equivalent found on this site. Please contact your system administrators.");

	define("IMPORT_ZIP_FAIL","You can only import zip files");
	
	define("IMPORT_XERTE_ONLY","Only Xerte templates are currently imported");
	
	define("IMPORT_ZIP_FOLDER_LEVEL","The files in your zip folder need to be in the main folder, not within another folder in the zip.");

    define("IMPORT_NOT_WRITABLE", "The folder needs to writable.");

    define("IMPORT_FAILED", "Import failed with a generic error. Is the file too large?");

    define("IMPORT_CHECKS_FAILED", "Checks on the imported files have failed");

