<?php

define("USER_SETTINGS_PASSWORD_TITLE", "Wachtwoord wijzigen");
define("USER_SETTINGS_PASSWORD_DISPLAY_TITLE", "Wachtwoord wijzigen");
define("USER_SETTINGS_PASSWORD_OLD", "Huidig wachtwoord");
define("USER_SETTINGS_PASSWORD_NEW", "Nieuw wachtwoord");
define("USER_SETTINGS_PASSWORD_NEW_REPEAT", "Herhaal nieuw wachtwoord");
define("USER_SETTINGS_PASSWORD_SUBMIT", "Wachtwoord wijzigen");

define("USER_SETTINGS_PREFERENCES_TITLE", "Mijn voorkeuren");
define("USER_SETTINGS_SECTION_EDITOR_OPEN", "Als ik een les open om te bewerken");
define("USER_SETTINGS_SECTION_OVERVIEW", "Op mijn overzichtspagina");
define("USER_SETTINGS_SECTION_IN_EDITOR", "In de editor");
define("USER_SETTINGS_EDITOR_OPEN_MODE_POPUP", "Open in een apart venster");
define("USER_SETTINGS_EDITOR_OPEN_MODE_BLANK", "Open in een nieuw tabblad");
define("USER_SETTINGS_EDITOR_OPEN_MODE_LIGHTBOX", "Open in een overlay op de overzichtspagina");
define("USER_SETTINGS_PANEL_EAST", "Toon de project templates rechts");
define("USER_SETTINGS_PANEL_SOUTH", "Toon de balk onderaan");
define("USER_SETTINGS_EDITOR_PANEL_EAST", "Toon het hulpvenster rechts");
define("USER_SETTINGS_EDITOR_SHOW_LANGUAGE", "Toon taalopties");
define("USER_SETTINGS_EDITOR_SHOW_TOOLBAR", "Toon bewerkingsknoppen");
define("USER_SETTINGS_EDITOR_EXPAND_GROUPS", "Open mappen automatisch");
define("USER_SETTINGS_EDITOR_EXPAND_TREE", "Open inhoudsstructuur automatisch");
define("USER_SETTINGS_CANCEL", "Annuleren");
define("USER_SETTINGS_SAVE", "Opslaan");

?>
