<?PHP     

	/**
	 * 
	 * Simile Edit english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("SIMILE_EDIT_TITLE", "Simile Editor Window");
	
	define("SIMILE_DESC_TEXT", "Enter the description for your timeline here. You can use &lt;p&gt;, &lt;img&gt; and &lt;a&gt; HTML tags.");
	
	define("SIMILE_START_STOP", "Timeline start and end years");
	
	define("SIMILE_START", "Start");
	
	define("SIMILE_STOP", "Stop");
	
	define("SIMILE_START_STOP_EXTRA" , "In these fields enter the years you want your timeline to start and stop.");
	
	define("SIMILE_ZONE", "Timeline zones");
	
	define("SIMILE_ZONE_EXPLAIN", "A zone is a band on the time zone reflecting a grouping of events");
	
	define("SIMILE_EXISTING_ZONES", "Existing zones");
	
	define("SIMILE_UNIT", "Unit");
	
	define("SIMILE_WIDTH", "Width");
	
	define("SIMILE_HOUR", "Hour");
	define("SIMILE_DAY", "Day");
	define("SIMILE_MONTH", "Month");
	define("SIMILE_YEAR", "Year");
	define("SIMILE_DECADE", "Decade");
	define("SIMILE_CENTURY", "Century");
	
	define("SIMILE_ZONE_GUIDE", "Which Time Zones should this zone sync with? (Make sure each zone is only linked to once.) ");
	
	define("SIMILE_ZONE_SYNC", "Select a zone to sync");
	define("SIMILE_REMOVE", "Remove");
	
	
	
	define("XERTE_EDIT_MAXIMISE", "Maximise Window Size");
	
?>