<?PHP

	/**
	 *
	 * export page template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("XERTE_EXPORT_DESCRIPTION", "Exported projects are downloaded to your computer in a zip file. The original project is not deleted and will remain in Xerte. There are several ways to export a project.");
	
    define("XERTE_EXPORT_INTERFACE", "Export interface:");
    define("XERTE_EXPORT_HTML5", "HTML5");
    define("XERTE_EXPORT_FLASH", "Flash (please note that Flash is no longer supported)");

	define("XERTE_EXPORT_ZIP_TITLE", "Deployment export");
	define("XERTE_EXPORT_ZIP", "Contains only the files required for importing into a VLE/LMS (without SCORM tracking), deploying onto a web server, or for importing into another Xerte installation.");
	define("XERTE_EXPORT_ZIP_LINK","Get deployment zip");

	define("XERTE_EXPORT_SCORM_TITLE", "SCORM export");
	define("XERTE_EXPORT_SCORM", "Self contained, SCORM 1.2 or SCORM 2004 enables tracking of interactivity scores e.g. into your LMS/VLE gradebook.");
	define("XERTE_EXPORT_SCORM_12_LINK","Get SCORM 1.2 package");
	define("XERTE_EXPORT_SCORM_2004_LINK","Get SCORM 2004 3rd Ed package");

    define("XERTE_EXPORT_ZIP_ARCHIVE_TITLE", "Archive export");
    define("XERTE_EXPORT_ZIP_ARCHIVE", "Complete export only really needed for troubleshooting xml or other issues.");
    define("XERTE_EXPORT_ZIP_ARCHIVE_LINK","Get archive zip");

    define("XERTE_EXPORT_ZIP_OFFLINE_TITLE", "Offline export");
    define("XERTE_EXPORT_ZIP_OFFLINE", "Special offline package that can be used offline. Double-click on the index.htm file stored on a local disk or USB stick.");
    define("XERTE_EXPORT_ZIP_OFFLINE_LINK","Get offline zip");
	
	define("XERTE_EXPORT_XAPI", "Export for xAPI (TinCan) deployment");
	define("XERTE_EXPORT_XAPI_LINK","Get xAPI (TinCan) package");

	
	


