<?PHP     

	/**
	 * 
	 * Xerte peer english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("XERTE_PEER_DESCRIPTION", "Peer review page");
	
	define("XERTE_PEER_GUIDANCE", "Please review this learning object. Use the feedback form below to submit your feedback.");
	
	define("XERTE_PEER_TEXTAREA_INSTRUCTIONS", "You have been asked to provide some feedback on this learning object. Please enter your feedback and click save when you have finished. This feedback is anonymous.");

    define("XERTE_PEER_BUTTON_SEND", "Send");

    define("XERTE_PEER_PASSWORD", "Password");

    define("XERTE_PEER_LOGIN_BUTTON", "Sign In");

?>