<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("EXTEND_LOGIN","Dodawanie nowego modułu");

    define("EXTEND_BUTTON_LOGIN","Zaloguj się");

    define("EXTEND_NOT_ADMIN_USERNAME","To jest nowy panel modułów. Tylko administratorzy strony mają dostęp do tego zasobu");
	
	define("EXTEND_USERNAME_AND_PASSWORD_EMPTY","Proszę wprowadzić swoją nazwę użytkownika i hasło");
	
	define("EXTEND_USERNAME_EMPTY","Proszę wprowadzić swoją nazwę użytkownika");
	
	define("EXTEND_PASSWORD_EMPTY","Proszę wprowadzić swoje hasło");
	
	define("EXTEND_LOGON_FAIL","Przepraszamy, kombinacja hasła nie jest prawidłowa");
	
	define("EXTEND_TITLE","Dodawanie nowych cech");
	
	define("EXTEND_LOGOUT","Wyloguj się");
	
	define("EXTEND_AUTHOR","Autor");
	
	define("EXTEND_CREATED","Utworzony");
	
	define("EXTEND_SIZE","Rozmiar");
	
	define("EXTEND_VISIT","Odwiedź stronę modułu");
	
	define("EXTEND_ALREADY","Już zainstalowano");
	
	define("EXTEND_UPGRADE","Aktualizuj");
	
	define("EXTEND_INSTALL","Instaluj");
	
	define("EXTEND_INSTALLED"," został zainstalowany ");
	
	define("EXTEND_ACTIVATE", "Aktywuj");
	
	define("EXTEND_LIST", "Lista modułów");
	
	define("EXTEND_MODULE_UPDATE", "Moduł zaktualizowany"); 
	
	define("EXTEND_MODULE_INSTALL", "Moduł zainstalowany"); 
	
	define("EXTEND_MODULE_REQUIRES", "Wymagania modułu");
	
	
?>