<?PHP 

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("FOLDERPROPERTIES_TITLE", "Właściwości folderu");

	define("FOLDERPROPERTIES_DISPLAY_TITLE", "Właściwości folderu");

	define("FOLDERPROPERTIES_TAB_FOLDER", "Właściwości folderu");

	define("FOLDERPROPERTIES_TAB_CONTENT", "Zawartość folderu");

	define("FOLDERPROPERTIES_TAB_RSS", "Kanał RSS folderu");

?>