<?php

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */
 
define("INDEX_USERNAME_AND_PASSWORD_EMPTY", "Wprowadź swoją nazwę użytkownika i hasło");

define("INDEX_USERNAME_EMPTY", "Wprowadź swoją nazwę użytkownika");

define("INDEX_PASSWORD_EMPTY", "Wprowadź swoje hasło");

define("INDEX_LDAP_MISSING", "Biblioteka PHP LDAP musi być zainstalowana, jeżeli chcesz użyć uwierzytelniania LDAP. Przeczytaj dalsze dostępne instrukcje i inne opcje");

define("INDEX_SITE_ADMIN", "Administratorzy strony powinni zalogować się na stronie zarządzania");

define("INDEX_LOGON_FAIL", "Przepraszamy ale ta kombinacja hasła nie jest poprawna");

define("INDEX_LOGIN", "obszar logowania");

define("INDEX_USERNAME", "Nazwa użytkownika");

define("INDEX_PASSWORD", "Hasło");

define("INDEX_HELP_TITLE", "Pierwsze kroki");

define("INDEX_HELP_INTRODUCTION", "Przygotowaliśmy krótkie wprowadzenie do strony narzędzi.");

define("INDEX_HELP_INTRO_LINK_TEXT","Pokaż mi!");

define("INDEX_NO_LDAP","Biblioteka PHP LDAP musi być zainstalowana, jeżeli chcesz użyć uwierzytelniania LDAP. Przeczytaj dalsze dostępne instrukcje i inne opcje");

define("INDEX_FOLDER_PROMPT","Jak chcesz nazwać swój folder?");

define("INDEX_WORKSPACE_TITLE","Moje projekty");

define("INDEX_CREATE","Utwórz nowy projekt");


define("INDEX_TEMPLATES","Tutaj są obecnie dostępne szablony.");

define("INDEX_SORT","Sortuj swoje pliki");

define("INDEX_SORT_A","Alfabetycznie A-Z");

define("INDEX_SORT_Z","Alfabetycznie Z-A");

define("INDEX_SORT_NEW","Wiek (Nowsze-Starsze)");

define("INDEX_SORT_OLD","Wiek (Starsze-Nowsze)");

define("INDEX_LOG_OUT","Wyloguj");

define("INDEX_LOGGED_IN_AS","Zalogowany jako");

define("INDEX_BUTTON_LOGIN","Zaloguj się");

define("INDEX_BUTTON_LOGOUT","Wyloguj się");

define("INDEX_BUTTON_PROPERTIES","Właściwości");

define("INDEX_BUTTON_EDIT","Edytuj");

define("INDEX_BUTTON_PREVIEW", "Podgląd");

define("INDEX_BUTTON_SORT", "Sortuj");

define("INDEX_BUTTON_NEWFOLDER", "Nowy folder");

define("INDEX_BUTTON_NEWFOLDER_CREATE", "Utwórz");

define("INDEX_BUTTON_DELETE", "Skasuj");

define("INDEX_BUTTON_DUPLICATE", "Powiel");

define("INDEX_BUTTON_PUBLISH", "Publikuj");

define("INDEX_BUTTON_CANCEL", "Anuluj");

define("INDEX_BUTTON_SAVE", "Zapisz");


?>
