<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("MANAGEMENT_LOGIN","obszar logowania dla administratorów");

    define("MANAGEMENT_BUTTON_LOGIN","Zaloguj się");

    define("MANAGEMENT_NOT_ADMIN_USERNAME","To jest panel zarządzania. Tylko administratorzy strony mają dostęp do tego zasobu");
	
	define("MANAGEMENT_USERNAME_AND_PASSWORD_EMPTY","Proszę wprowadzić swoją nazwę użytkownika i hasło");
	
	define("MANAGEMENT_USERNAME_EMPTY","Proszę wprowadzić swoją nazwę użytkownika");
	
	define("MANAGEMENT_PASSWORD_EMPTY","Proszę wprowadzić swoje hasło");
	
	define("MANAGEMENT_LOGON_FAIL","Przepraszamy, kombinacja hasła nie jest poprawna");
	
	define("MANAGEMENT_LOGOUT","Wyloguj się");
	
	define("MANAGEMENT_TITLE","Strona administracji");
	
	define("MANAGEMENT_MENUBAR_SITE","Strona");
	
	define("MANAGEMENT_MENUBAR_CENTRAL","Centrum szablonów");
	
	define("MANAGEMENT_MENUBAR_USERS","Użytkownicy");
	
	define("MANAGEMENT_MENUBAR_TEMPLATES","Użytkownicy szablonów");
	
	define("MANAGEMENT_MENUBAR_ERRORS","Błędy");
	
	define("MANAGEMENT_MENUBAR_PLAY","Bezpieczeństwo odtwarzania");
	
	define("MANAGEMENT_MENUBAR_CATEGORIES","Kategorie");
	
	define("MANAGEMENT_MENUBAR_LICENCES","Licencje");
	
	define("MANAGEMENT_MENUBAR_FEEDS","Kanały");
	
	define("MANAGEMENT_MENUBAR_SAVE","Zapisz");
	
?>