<?PHP 

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("PROPERTIES_TITLE","Właściwości projektu");
	define("PROPERTIES_DISPLAY_TITLE","Właściwości projektu");
	define("PROPERTIES_TAB_PROJECT","Projekt");
	define("PROPERTIES_TAB_NOTES","Notatki");
	define("PROPERTIES_TAB_MEDIA","Media i pojemność");
	define("PROPERTIES_TAB_ACCESS","Dostęp");
	define("PROPERTIES_TAB_SHARED","Ustawienia udostępniania");
	define("PROPERTIES_TAB_RSS","RSS");
	define("PROPERTIES_TAB_OPEN","Otwarta zawartość");
	define("PROPERTIES_TAB_EXPORT","Eksport");
	define("PROPERTIES_TAB_PEER","Wzajemna ocena");
	define("PROPERTIES_TAB_GIVE","Daj ten projekt");
	define("PROPERTIES_TAB_XML","dzielenie XML");

?>