<?PHP 

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("PUBLISH_PROPERTIES_TITLE","Publikowanie twojego projektu");
	define("PUBLISH_PROPERTIES_DISPLAY_TITLE","Publikowanie twojego projektu");
	define("PUBLISH_PROPERTIES_TAB_PROJECT","Projekt");
	define("PUBLISH_PROPERTIES_TAB_ACCESS","Dostęp");
	define("PUBLISH_PROPERTIES_TAB_RSS","RSS");
	define("PUBLISH_PROPERTIES_TAB_OPEN","Otwarta zawartość");
	
?>
