<?PHP 

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("RSS_DESCRIPTION","Kanał zawierający wszystkie publiczne obiekty nauczania z");
	define("RSS_LANGUAGE","pl-pl");
	define("RSS_DB_FAIL","Przepraszamy, system nie może się w tej chwili połączyć się z bazą danych. Wystąpił błąd ");
	define("RSS_LO","obiektów nauczania");
	define("RSS_PLURAL", "");
	define("RSS_FEED_DESC","Kanał zawierający wszystkie"); 
	define("RSS_FEED_PUBLIC","publiczne obiekty nauczania z ");
	define("RSS_USER_LO","obiektów nauczania ");
	define("RSS_FEED_USER","Kanał zawierający wszystkie ");
	define("RSS_USER_LO_LOWER","obiektów nauczania - ");
	define("RSS_FROM"," z ");
	define("RSS_SITE"," strony ");
	define("RSS_DEVELOP"," został opracowany przez ");
 
 ?>