<?PHP 

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("SYNDICATE_DESCRIPTION","Ten kanał RSS zawiera listę wszystkich syndykowanych zawartości z instalacji Zestawu Narzędzi Xerte Online ");
	define("SYNDICATE_LANGUAGE","pl-pl");
	define("SYNDICATE_DOWNLOAD","Ściągnij tą zawartość z ");
	define("SYNDICATE_DOWNLOAD_SCORM","Ściągnij to jako pakiet scorm z");
	define("SYNDICATE_LICENCE","Ta zawartość ma poniższą licencję");

?>