<?PHP 

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("WORKSPACE_PROPERTIES_TITLE","Właściwości obszaru roboczego użytkownika");
	define("WORKSPACE_PROPERTIES_DISPLAY_TITLE","Właściwości obszaru roboczego");
	define("WORKSPACE_PROPERTIES_TAB_DETAILS","Moje szczegóły");
	define("WORKSPACE_PROPERTIES_TAB_PROJECTS","Moje projekty");
	define("WORKSPACE_PROPERTIES_TAB_FEEDS","Moje kanały");
	define("WORKSPACE_PROPERTIES_TAB_IMPORT","Importuj");
	define("WORKSPACE_PROPERTIES_TAB_API","API");
	
?>