<?php
/**
 * Created by JetBrains PhpStorm.
 * User: tom
 * Date: 22-3-13
 * Time: 10:48
 * To change this template use File | Settings | File Templates.
 */

define("DELETE_LANGUAGE_SUCCEEDED", "Language definition successfully deleted: ");
define("DELETE_LANGUAGE_FAILED", "Deletion of fanguage definition failed:\n");
define("DELETE_LANGUAGE_WRITABLE", " needs to be writeable. Cannot perform installation");
define("DELETE_LANGUAGE_INVALIDCODE", " No valid language code given!");
define("DELETE_LANGUAGE_UNABLE_TO_DELETE", " Unable to delete ");
?>