<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	// XML SHARING TAB

	define("GIFT_RESPONSE_FAIL", "Przepraszamy, nie masz już praw do tego szablonu");
	
	define("GIFT_RESPONSE_SUCCESS", "Pomyślnie podarowano projekt");
			
	define("GIFT_RESPONSE_INSTRUCTIONS","Aby komuś dać ten projekt, proszę wprowadzić tutaj jego nazwę");
			
	define("GIFT_RESPONSE_NAMES","Nazwy powinny pojawić się tutaj");

?>