<?PHP 

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	// XML SHARING TAB

	define("MEDIA_AND_QUOTA_USE", "W użyciu");

	define("MEDIA_AND_QUOTA_IMPORT_MEDIA", "Importuj media");

	define("MEDIA_AND_QUOTA_CLICK_FILENAME", "Kliknij na nazwie pliku a pojawi się poniżej link");

	define("MEDIA_AND_QUOTA_BUTTON_IMPORT", "Importuj");

	define("MEDIA_AND_QUOTA_DOWNLOAD", "Ściągnij ten plik");
	
	define("MEDIA_AND_QUOTA_NOT_IN_USE", "Nie w użyciu");
	
	define("MEDIA_AND_QUOTA_DELETE", "Kliknij aby skasować");
	
	define("MEDIA_AND_QUOTA_USAGE", "Ten projekt jest obecnie używany");

	define("MEDIA_AND_QUOTA_UPLOAD", "Załaduj");

	define("MEDIA_AND_QUOTA_LINK", "Kliknij na nazwie pliku a pojawi się poniżej link");
	
	define("MEDIA_AND_QUOTA_PUBLISH", "W użyciu / nie w użyciu odnosi do tego, czy plik jest używany w wersji opublikowanej, nie w wersji roboczej");
	
	define("MEDIA_AND_QUOTA_FAIL", "Przepraszamy, nie masz uprawnień do tego szablonu");

?>