<?PHP

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

    define("PROPERTIES_LIBRARY_SAVE", "Zapisz");

    define("PROPERTIES_LIBRARY_RENAME", "Zmień nazwę");

	// XML SHARING TAB

	define("PROPERTIES_LIBRARY_XML_TITLE", "Udostępnianie XML");
	
	define("PROPERTIES_LIBRARY_XML_DESCRIPTION", "W tej sekcji możesz ustawić udostępnianie XML dla jednego z twoich projektów. Aby to działało, twój projekt musi być opublikowany. To pozwala twojej pracy być używaną w innych systemach");
	
	define("PROPERTIES_LIBRARY_XML_SHARING", "Udostępnianie XML jest");
	
	define("PROPERTIES_LIBRARY_ON", "włączone");
	
	define("PROPERTIES_LIBRARY_OFF", "wyłączony");
			
	define("PROPERTIES_LIBRARY_XML_RESTRICT", "Jeżeli chcesz, możesz ograniczyć dotęp do jednej strony");
	
	define("PROPERTIES_LIBRARY_XML_SAVE", "Twoje zmiany zostały zapisane");
	
	define("PROPERTIES_LIBRARY_XML_ERROR", "Przepraszamy, tylko autorzy szablonów mogą ustawiać udostępnianie XML");
	
	
	// PROJECT TAB
	
	define("PROPERTIES_LIBRARY_PROJECT", "Projekt");
	
	define("PROPERTIES_LIBRARY_PROJECT_NAME", "Nazwa projektu");
	
	define("PROPERTIES_LIBRARY_PROJECT_CHANGED", "Nazwa zmieniona");
	
	define("PROPERTIES_LIBRARY_PROJECT_CREATE", "Plik został utworzony");
	
	define("PROPERTIES_LIBRARY_PROJECT_MODIFY", "Plik został ostatnio zmodyfikowany");

    define("PROPERTIES_LIBRARY_DEFAULT_ENGINE", "Który silnik jest domyślnie używany przy tym projekcie?");

    define("PROPERTIES_LIBRARY_PUBLISH_ENGINE", "Domyślny silnik");

    define("PROPERTIES_LIBRARY_DEFAULT_HTML5", "Javascript (HTML5)");

    define("PROPERTIES_LIBRARY_DEFAULT_FLASH", "Flash");

    define("PROPERTIES_LIBRARY_DEFAULT_ENGINE_CHANGED", "Domyślny silnik został zmieniony.");

	define("PROPERTIES_LIBRARY_PROJECT_LINK", "Pozwól innym ludziom na dostęp do tego pliku, link to");
	
	define("PROPERTIES_LIBRARY_PROJECT_HTML5_LINK", "Pozwól innym ludziom na dostęp do wersji HTML 5, link to");
	
	define("PROPERTIES_LIBRARY_PROJECT_IFRAME", "Ten kod pozwala tobie osadzać twój projekt na stronie www");
			
	define("PROPERTIES_LIBRARY_PROJECT_FAIL", "Przepraszamy, nie masz uprawnień do tego szablonu");
	
	
	// NOTES TAB
	
	define("PROPERTIES_LIBRARY_NOTES", "Uwagi projektu:");
	
	define("PROPERTIES_LIBRARY_NOTES_EXPLAINED", "Te uwagi są tylko widoczne dla ciebie");
	
	define("PROPERTIES_LIBRARY_NOTES_SAVED", "Uwagi zapisane");
	
	define("PROPERTIES_LIBRARY_NOTES_FAIL", "Przepraszamy, tylko twórca pliku może notować uwagi dla projektu");
	
	
	// PEER TAB
	
	define("PROPERTIES_LIBRARY_PEER", "Wzajemna ocena");
	
	define("PROPERTIES_LIBRARY_PEER_EXPLAINED", "W tej sekcji możesz ustawiać wzajemną ocenę dla jednego z twoich projektów. To pozwala tobie wysyłać zakodowany hasłem link do pracowników, pozwalając im na dostęp do projektu, i dając im łatwe emailowane na twoją odpowiedź");
		
	define("PROPERTIES_LIBRARY_PEER_STATUS", "Wzajemna ocena jest ");

    define("PROPERTIES_LIBRARY_PEER_LINK", "Link dla wzajemnej oceny jest ");

    define("PROPERTIES_LIBRARY_PEER_PASSWORD_PROMPT", "Hasło do dania dla recenzentów ");

    define("PROPERTIES_LIBRARY_PEER_RETOUREMAIL_PROMPT", "Adresy e-mail (oddzielone przez ',') do wysłania odpowiedzi zwrotnej do ");

	define("PROPERTIES_LIBRARY_PEER_SAVED", "Ustawienia wzajemnej oceny zmieniono");
			
	define("PROPERTIES_LIBRARY_PEER_FAIL", "Przepraszamy, tylko twórcy szablonów mogą ustawiać wzajemną ocenę");
	
	
	// SYNDICATION TAB
	
	define("PROPERTIES_LIBRARY_SYNDICATION", "Otwarta zawartość");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_EXPLAINED", "Ta zakładka pozwala tobie załączyć projekt na listę otwartych treści. Otwarte treści są rozumiane jako materiały publikowane przez instytucję, dostępne do użycia dla każdego. Adres dla tej strony syndykowanej treści to");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_PROMPT", "Załącz ten projekt do Kanału Otwartej Zawartości");	

	define("PROPERTIES_LIBRARY_YES", "Tak");

	define("PROPERTIES_LIBRARY_NO", "Nie");

	define("PROPERTIES_LIBRARY_SYNDICATION_CATEGORY", "Proszę wybrać kategorię dla swojego projektu");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_LICENCE", "Proszę wybrać licencję dla swojego projektu");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_DESCRIPTION", "Proszę dostarczyć opis dla swojego projektu");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_KEYWORDS", "Proszę dostarczyć listę słów kluczowych oddzielonymi przecinkami dla tego projektu");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_SAVED", "Twoje zmiany zostały zapisane");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_PUBLIC", "Proszę ustawić ten projekt na 'Publiczny' na zakładce dostępu przed użyciem syndykacji");
	
	define("PROPERTIES_LIBRARY_SYNDICATION_URL", "Adres dla tej strony syndykowanej zawartości to");

	define("PROPERTIES_LIBRARY_SYNDICATION_FAIL", "Przepraszamy, tylko twórca pliku może ustawić syndykację dla projektu");
	
	
	
	
	// ACCESS TAB
	
	define("PROPERTIES_LIBRARY_ACCESS", "Ten plik jest obecnie używany jako"); 

	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC", "Publiczny");

	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC_EXPLAINED", "Szablon może być widoczny dla każdego w Internecie");
		
	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD", "Chronione hasłem");
		
	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD_EXPLAINED", "Szablon może być widoczny dla ludzi mających konto w tym systemie");
		
	define("PROPERTIES_LIBRARY_ACCESS_OTHER", "Inni");
		
	define("PROPERTIES_LIBRARY_ACCESS_OTHER_EXPLAINED", "Użyj tego ustawienia aby ograniczyć dostęp do twojej zawartości. Twoja zawartość będzie widoczna dla ludzi posiadających linki do twojej zawartości ze strony, na której te linki umieściłeś. Wprowadź poniżej adres URL.");
		
	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE", "Prywatny");
		
	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE_EXPLAINED", "To sprawi, że twój szablon będzie widoczny tylko dla redaktorów.");
		
	define("PROPERTIES_LIBRARY_ACCESS_FAIL", "Przepraszamy, tylko twórca może ustawić te ustawienie dostępu");
	
	define("PROPERTIES_LIBRARY_ACCESS_BUTTON_CHANGE", "Zmiana dostępu");

    define("PROPERTIES_LIBRARY_ACCESS_CHANGED", "Nowe ustawienia dostępu zostały zapisane.");

	// RSS TAB
	
	define("PROPERTIES_LIBRARY_RSS", "Kanały RSS");
	
	define("PROPERTIES_LIBRARY_RSS_INCLUDE", "Załącz ten projekt w kanałach RSS"); 
	
	define("PROPERTIES_LIBRARY_RSS_DESCRIPTION", "Jeżeli chcesz, możesz także załączyć opis dla swojego projektu w kanale RSS");
	
	define("PROPERTIES_LIBRARY_RSS_SITE", "Możesz załączyć tą zawartość w kanałach RSS strony. Ludzie, którzy zaprenumerowują kanały, będą widzieć nową zawartość jako dodaną do kanałów. Jest tam kilka dostępnych kanałów");

	define("PROPERTIES_LIBRARY_RSS_SITE_LINK", "Główny kanał jest na");
	
	define("PROPERTIES_LIBRARY_RSS_PERSONAL", "To załącza całą zawartość oznaczoną do uwzględnienia przez użytkowników strony. <BR><BR> Twój własny kanał RSS jest dostępny na"); 
	
	define("PROPERTIES_LIBRARY_RSS_MINE", "To tylko załącza zawartość którą masz oznaczoną do uwzględnienia.");

	define("PROPERTIES_LIBRARY_RSS_FOLDER", "Jak sobie zorganizujesz zawartość w folderach, każdy folder ma swój własny kanał RSS. To dostarcza wygodną drogę do załączenia tylko jakiejś zawartości na kanale. Zobacz właściwości folderu aby uzyskać więcej szczegółów, i link kanału do tego folderu");

	define("PROPERTIES_LIBRARY_RSS_EXPORT", "Załączając zawartość w eksporcie kanału pozwalasz innym użytkownikom ściągać swój projekt i dokonywać swoich własnych zmian");

	define("PROPERTIES_LIBRARY_RSS_SAVED", "Twoje zmiany zostały zapisane");
	
	define("PROPERTIES_LIBRARY_RSS_PUBLIC", "Proszę ustawić ten projekt na 'Publiczny' na zakładce dostępu przed użciem Kanału RSS");
	
	define("PROPERTIES_LIBRARY_RSS_FAIL", "Przepraszamy, tylko twórca pliku może ustalać uwagi dla projektu");

	
?>
	
