<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("PUBLISH_TITLE","Projekt");

	define("PUBLISH_DESCRIPTION","Ten panel zawiera wszystkie ustawienia, potrzebne do opublikowania twojego projektu.");

	define("PUBLISH_ACCESS","Dostęp");
	
	define("PUBLISH_ACCESS_DESCRIPTION","Jeżeli wcześniej ten  projekt nie był publikowany, musisz wybrać właściwą opcję w zakładce 'Dostęp'. To kontroluje w jaki sposób twoi użytkownicy mają dostęp do twoich treści. Aby ustawić opcje dostępu, wybierz zakładkę 'Dostęp' i podążaj za instrukcjami");
	
	define("PUBLISH_ACCESS_STATUS","Twój projekt jest obecnie prywatny. Wybierz 'Dostęp' aby zmienić to");
	
	define("PUBLISH_ACCESS_IS","Twój projekt jest obecnie ustawiony jako");
	
	define("PUBLISH_RSS","RSS");
	
	define("PUBLISH_RSS_DESCRIPTION","Kanały RSS dostarczają prostą drogę dla twoich użytkowników do aktualnych zawartości. Jeżeli chcesz dodać ten projekt do twoich kanałów RSS, wybierz zakładkę 'RSS' i podążaj za instrukcjami");
	
	define("PUBLISH_RSS_NOT_INCLUDE","Twój projekt nie jest w żadnym kanale RSS");
	
	define("PUBLISH_RSS_INCLUDE","Twój projekt jest dostępny w kanałach RSS");
	
	define("PUBLISH_SYNDICATION","Syndykacja");
	
	define("PUBLISH_SYNDICATION_DESCRIPTION","Syndykacja twojej zawartości tworzy ją dostępną dla szerszego grona przez tworzenie repozytorium otwarto-dostępowej zawartości. Aby syndykować swój projekt, wybierz zakładkę 'Syndykacja' i podążaj za instrukcjami");
	
	define("PUBLISH_SYNDICATION_STATUS_OFF","Twój projekt nie jest obecnie syndykowany.");
	
	define("PUBLISH_SYNDICATION_STATUS_ON","Twój projekt jest obecnie syndykowany");

    define ("PUBLISH_BUTTON_LABEL", "Publikuj");

    define("PUBLISH_WEB_ADDRESS","Adres www do tego zasobu to ");
	
	define("PUBLISH_FAIL","Przepraszamy, ale nie masz praw do tego szablonu");
	
?>