<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("SHARING_INSTRUCTION","Aby udostępnić komuś ten szablon, proszę wprowadzić tutaj jego nazwę. Użytkownik musi mieć konto w systemie przed dokonaniem wyszukiwania.");
	
	define("SHARING_NAMES","Nazwy pojawią się tutaj");

	define("SHARING_CURRENT","Ten szablon jest obecnie dostępny dla : ");

	define("SHARING_EDITOR","Redaktor");

	define("SHARING_READONLY","Tylko do odczytu");

    define("SHARING_REMOVE_DESCRIPTION", "Naciśnij poniższy przycisk, aby usunąć wszystkie prawa udostępniania");

    define("SHARING_REMOVE", "Usuń");

	define("SHARING_STOP","Kliknij, aby przestać udostępniać ten plik");

	define("SHARING_NOT_SHARED","Ten szablon nie jest udostępniany");

	define("SHARING_FAIL","Nie masz praw do tego szablonu");

?>