<?php

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

define("DELETE_LANGUAGE_SUCCEEDED", "Definicja języka pomyślnie skasowana: ");
define("DELETE_LANGUAGE_FAILED", "Skasowanie definicji języka niepowiodło się:\n");
define("DELETE_LANGUAGE_WRITABLE", "  potrzebuje praw do zapisu. Nie można kontynuować instalacji");
define("DELETE_LANGUAGE_INVALIDCODE", " Podano niepoprawny kod języka!");
define("DELETE_LANGUAGE_UNABLE_TO_DELETE", " Nie można skasować ");
?>