<?php

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

    define("IMPORT_LANGUAGE_SUCCEEDED", "Definicja języka została zainstalowana: ");
    define("IMPORT_LANGUAGE_FAILED", " instalacja definicji języka niepowiodła się:\n");
    define("IMPORT_LANGUAGE_WRITABLE", " potrzebuje praw do zapisu. Nie można kontynuować instalacji");
    define("IMPORT_LANGUAGE_NOVALIDZIP", " Nie znaleziono w pliku definicji języka!");
?>