<?PHP     

	/**
	 * 
	 * peer review language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("PEER_REVIEW_FEEDBACK","Feedback on project");
	
	define("PEER_REVIEW_EMAIL_GREETING","Hello,");
	
	define("PEER_REVIEW_EMAIL_INTRO","You've received feedback on your project.");
	
	define("PEER_REVIEW_EMAIL_YOURS","Thanks for using the site");
	
	define("PEER_REVIEW_EMAIL_SIGNATURE","The Xerte Project Team");

	define("PEER_REVIEW_USER_FEEDBACK","Your feedback has been sent to the user");
	
	define("PEER_REVIEW_PROBLEM","A problem has occured");
	
?>