<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("PEER_REVIEW_FEEDBACK","Feedback on project");

	define("PEER_REVIEW_EMAIL_GREETING","Hello,");

	define("PEER_REVIEW_EMAIL_INTRO","You've received feedback on your project:");

	define("PEER_REVIEW_EMAIL_YOURS","Thanks for using Xerte");

	define("PEER_REVIEW_EMAIL_SIGNATURE","The Xerte Project");

    define("PEER_REVIEW_IDENTIFICATION","This email was sent as feedback on learning object {template_id} created by {creator} using the Xerte installation hosted at {url}");

    define("PEER_REVIEW_USER_FEEDBACK","Your feedback has been sent to the user");

	define("PEER_REVIEW_PROBLEM","A problem has occured");
