<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
	 
	define("EXTEND_LOGIN","Adding new modules");

    define("EXTEND_BUTTON_LOGIN","Login");

    define("EXTEND_NOT_ADMIN_USERNAME","This is the new modules panel. Only site administrators can access this resource");
	
	define("EXTEND_USERNAME_AND_PASSWORD_EMPTY","Please enter your username and password");
	
	define("EXTEND_USERNAME_EMPTY","Please enter your username");
	
	define("EXTEND_PASSWORD_EMPTY","Please enter your password");
	
	define("EXTEND_LOGON_FAIL","Sorry that password combination was not correct");
	
	define("EXTEND_TITLE","Adding new features");
	
	define("EXTEND_LOGOUT","Log out");
	
	define("EXTEND_AUTHOR","Author");
	
	define("EXTEND_CREATED","Created");
	
	define("EXTEND_SIZE","Size");
	
	define("EXTEND_VISIT","Visit module page");
	
	define("EXTEND_ALREADY","Already installed");
	
	define("EXTEND_UPGRADE","Upgrade");
	
	define("EXTEND_INSTALL","Install");
	
	define("EXTEND_INSTALLED"," has been installed ");
	
	define("EXTEND_ACTIVATE", "Activate");
	
	define("EXTEND_LIST", "List Modules");
	
	define("EXTEND_MODULE_UPDATE", "Module updated"); 
	
	define("EXTEND_MODULE_INSTALL", "Module installed"); 
	
	define("EXTEND_MODULE_REQUIRES", "Module requires");
	
	
?>