<?PHP     

	/**
	 * 
	 * management.php english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("EXTEND_LOGIN","Adding new modules");

    define("EXTEND_BUTTON_LOGIN","Login");

    define("EXTEND_NOT_ADMIN_USERNAME","This is the new modules panel. Only site administrators can access this resource");
	
	define("EXTEND_USERNAME_AND_PASSWORD_EMPTY","Please enter your username and password");
	
	define("EXTEND_USERNAME_EMPTY","Please enter your username");
	
	define("EXTEND_PASSWORD_EMPTY","Please enter your password");
	
	define("EXTEND_LOGON_FAIL","Sorry that password combination was not correct");
	
	define("EXTEND_TITLE","Adding new features");
	
	define("EXTEND_LOGOUT","Log out");
	
	define("EXTEND_AUTHOR","Author");
	
	define("EXTEND_CREATED","Created");
	
	define("EXTEND_SIZE","Size");
	
	define("EXTEND_VISIT","Visit module page");
	
	define("EXTEND_ALREADY","Already installed");
	
	define("EXTEND_UPGRADE","Upgrade");
	
	define("EXTEND_INSTALL","Install");
	
	define("EXTEND_INSTALLED"," has been installed ");
	
	define("EXTEND_ACTIVATE", "Activate");
	
	define("EXTEND_LIST", "List Modules");
	
	define("EXTEND_MODULE_UPDATE", "Module updated"); 
	
	define("EXTEND_MODULE_INSTALL", "Module installed"); 
	
	define("EXTEND_MODULE_REQUIRES", "Module requires");
	
	
?>