<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

    define("XERTE_FEEDBACK_DESCRIPTION", "Providing Feedback");

    define("XERTE_FEEDBACK_GUIDANCE", "Please use the feedback form below to provide feedback on this resource. Simply enter your feedback and click send.");

define("XERTE_FEEDBACK_LIGHTBOX", "View in lightbox");

    define("XERTE_FEEDBACK_CONTACT_INSTRUCTIONS", "Important: This feedback is anonymous. If you wish to be contacted please add your name and contact details to your response before clicking send.");

    define("XERTE_FEEDBACK_BUTTON_SEND", "Send");
?>