<?PHP 

	/**
	 * 
	 * feedback.php english language file
	 *
	 * @author Ron Mitchell
	 * @version 1.0
	 * @copyright Ron Mitchell
	 * @package
	 */
	 

    define("XERTE_FEEDBACK_DESCRIPTION", "Providing Feedback");

    define("XERTE_FEEDBACK_GUIDANCE", "Please use the feedback form below to provide feedback on this resource. Simply enter your feedback and click send.");

define("XERTE_FEEDBACK_LIGHTBOX", "View in lightbox");

    define("XERTE_FEEDBACK_CONTACT_INSTRUCTIONS", "Important: This feedback is anonymous. If you wish to be contacted please add your name and contact details to your response before clicking send.");

    define("XERTE_FEEDBACK_BUTTON_SEND", "Send");
?>