<?PHP 

	/**
	 * 
	 * folder properties english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("FOLDERPROPERTIES_TITLE", "Folder properties");

	define("FOLDERPROPERTIES_DISPLAY_TITLE", "Folder Properties");

	define("FOLDERPROPERTIES_TAB_FOLDER", "Folder");

	define("FOLDERPROPERTIES_TAB_CONTENT", "Contents");

	define("FOLDERPROPERTIES_TAB_RSS", "RSS");

	define("FOLDERPROPERTIES_TAB_SHARED",  "Shared settings");
?>