<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
	 
	define("MANAGEMENT_LOGIN","Site administrator login:");

    define("MANAGEMENT_BUTTON_LOGIN","Log in");
	
	define("MANAGEMENT_USERNAME", "Username");

	define("MANAGEMENT_PASSWORD", "Password");

	define("MANAGEMENT_LOGO_ALT", "Site logo");

	define("MANAGEMENT_WCAG_LOGO_ALT", "W3C logo");

    define("MANAGEMENT_XERTE_AI_LOGO_ALT", "Xerte AI logo");

	define("MANAGEMENT_OSI_LOGO_ALT", "Open Source Initiative logo");

	define("MANAGEMENT_APEREO_LOGO_ALT", "Apereo logo");

	define("MANAGEMENT_XERTE_LOGO_ALT", "Xerte logo");

    define("MANAGEMENT_NOT_ADMIN_USERNAME","This is the management panel. Only site administrators can access this resource");
	
	define("MANAGEMENT_USERNAME_AND_PASSWORD_EMPTY","Please enter your username and password");
	
	define("MANAGEMENT_USERNAME_EMPTY","Please enter your username");
	
	define("MANAGEMENT_PASSWORD_EMPTY","Please enter your password");
	
	define("MANAGEMENT_LOGON_FAIL","Sorry that password combination was not correct");
	
	define("MANAGEMENT_LOGOUT","Log out");

	define("MANAGEMENT_TOWORKSPACE","Workspace");

	define("MANAGEMENT_TITLE","Site Administration");
	
	define("MANAGEMENT_MENUBAR_SITE","Site");
	
	define("MANAGEMENT_MENUBAR_CENTRAL","Templates");

	define("MANAGEMENT_MENUBAR_THEMES","Themes");
	
	define("MANAGEMENT_MENUBAR_USERS","Users");

	define("MANAGEMENT_MENUBAR_USER_GROUPS","User Groups");
	
	define("MANAGEMENT_MENUBAR_TEMPLATES","Users projects");
	
	define("MANAGEMENT_MENUBAR_LOGS","Log files");
	
	define("MANAGEMENT_MENUBAR_PLAY","Play security");
	
	define("MANAGEMENT_MENUBAR_CATEGORIES","Categories");

	define("MANAGEMENT_MENUBAR_EDUCATION", "Educations");

	define("MANAGEMENT_MENUBAR_GROUPINGS","Groupings");

	define("MANAGEMENT_MENUBAR_COURSES","Courses");

	define("MANAGEMENT_MENUBAR_LICENCES","Licences");

	define("MANAGEMENT_MENUBAR_AI","Ai");
	
	define("MANAGEMENT_MENUBAR_FEEDS","Feeds");
	
	define("MANAGEMENT_MENUBAR_SAVE","Save");

	define("MANAGEMENT_NEW_ROLES_ADDED_LOGIN_AS_ADMIN", "<h1>Admin roles</h1><p>New admin roles have been implemented and you don't have any admin role assigned to you. To assign roles to existing users you need to login as admin.</p><p>To login using the original admin credentials, please click the following link: <a href='index.php?login=admin'>Login as admin</a></p>");

    define("MANAGEMENT_TO_TSUGI_ADMIN", "LTI/TSUGI Admin Panel");

