<?PHP     

	/**
	 * 
	 * management.php english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("MANAGEMENT_LOGIN","login area for site administration");

    define("MANAGEMENT_BUTTON_LOGIN","Sign In");

    define("MANAGEMENT_NOT_ADMIN_USERNAME","This is the management panel. Only site administrators can access this resource");
	
	define("MANAGEMENT_USERNAME_AND_PASSWORD_EMPTY","Please enter your username and password");
	
	define("MANAGEMENT_USERNAME_EMPTY","Please enter your username");
	
	define("MANAGEMENT_PASSWORD_EMPTY","Please enter your password");
	
	define("MANAGEMENT_LOGON_FAIL","Sorry that password combination was not correct");
	
	define("MANAGEMENT_LOGOUT","Log out");
	
	define("MANAGEMENT_TITLE","Site Administration");
	
	define("MANAGEMENT_MENUBAR_SITE","Site");
	
	define("MANAGEMENT_MENUBAR_CENTRAL","Central templates");
	
	define("MANAGEMENT_MENUBAR_USERS","Users");
	
	define("MANAGEMENT_MENUBAR_TEMPLATES","Users templates");
	
	define("MANAGEMENT_MENUBAR_ERRORS","Errors");
	
	define("MANAGEMENT_MENUBAR_PLAY","Play security");
	
	define("MANAGEMENT_MENUBAR_CATEGORIES","Categories");
	
	define("MANAGEMENT_MENUBAR_LICENCES","Licences");
	
	define("MANAGEMENT_MENUBAR_FEEDS","Feeds");
	
	define("MANAGEMENT_MENUBAR_SAVE","Save");
	
?>