<?PHP 

	/**
	 * 
	 * peer.php english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("PEER_LOGON_FAIL","Sorry login has failed");

    define("XERTE_PEER_DESCRIPTION", "Peer review page");

    define("XERTE_PEER_GUIDANCE", "Please review this learning object. Use the feedback form below to submit your feedback.");

define("XERTE_PEER_LIGHTBOX", "View in lightbox");

    define("XERTE_PEER_TEXTAREA_INSTRUCTIONS", "You have been asked to provide some feedback on this learning object. Please enter your feedback and click send when you have finished. This feedback is anonymous. If you wish to be contacted please add your name and contact details to your response before clicking send.");

    define("XERTE_PEER_BUTTON_SEND", "Send");

    define("XERTE_PEER_PASSWORD", "Password");

    define("XERTE_PEER_LOGIN_BUTTON", "Sign In");
?>