<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
	 
	define("PROPERTIES_TITLE","Project properties");
	define("PROPERTIES_DISPLAY_TITLE","Project Properties");
	define("PROPERTIES_TAB_PROJECT","Project");
	define("PROPERTIES_TAB_NOTES","Notes");
	define("PROPERTIES_TAB_MEDIA","Media and files");
	define("PROPERTIES_TAB_ACCESS","Access");
	define("PROPERTIES_TAB_SHARED","Shared settings");
	define("PROPERTIES_TAB_RSS","RSS");
	define("PROPERTIES_TAB_OPEN","Open content");
	define("PROPERTIES_TAB_EXPORT","Export");
	define("PROPERTIES_TAB_TSUGI","LTI/xAPI");
	define("PROPERTIES_TAB_PEER","Peer review");
	define("PROPERTIES_TAB_GIVE","Give this project");
	define("PROPERTIES_TAB_XML","XML sharing");

?>