<?PHP 

	/**
	 * 
	 * properties english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("PROPERTIES_TITLE","Project properties");
	define("PROPERTIES_DISPLAY_TITLE","Project Properties");
	define("PROPERTIES_TAB_PROJECT","Project");
	define("PROPERTIES_TAB_NOTES","Notes");
	define("PROPERTIES_TAB_MEDIA","Media and quota");
	define("PROPERTIES_TAB_ACCESS","Access");
	define("PROPERTIES_TAB_SHARED","Shared settings");
	define("PROPERTIES_TAB_RSS","RSS");
	define("PROPERTIES_TAB_OPEN","Open Content");
	define("PROPERTIES_TAB_EXPORT","Export");
	define("PROPERTIES_TAB_PEER","Peer review");
	define("PROPERTIES_TAB_GIVE","Give this project");
	define("PROPERTIES_TAB_XML","XML sharing");

?>