<?PHP 

	/**
	 * 
	 * publish properties english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("PUBLISH_PROPERTIES_TITLE","Publishing your project");
	define("PUBLISH_PROPERTIES_DISPLAY_TITLE","Publishing your project");
	define("PUBLISH_PROPERTIES_TAB_PROJECT","Project");
	define("PUBLISH_PROPERTIES_TAB_ACCESS","Access");
	define("PUBLISH_PROPERTIES_TAB_RSS","RSS");
	define("PUBLISH_PROPERTIES_TAB_OPEN","Open Content");
	
?>
