<?PHP 

	/**
	 * 
	 * pwplay.php english language file
	 *
	 * @author Ron MItchell
	 * @version 1.0
	 * @copyright Ron MItchell
	 * @package
	 */
	 
	define("PWPLAY_LOGON_FAIL","Incorrect password");

    define("XERTE_PWPLAY_DESCRIPTION", "Password Protected");

    define("XERTE_PWPLAY_GUIDANCE", "This resource is password protected. To continue, please enter the password that you have been provided with below.");

    define("XERTE_PWPLAY_PASSWORD", "Password:");

    define("XERTE_PWPLAY_LOGIN_BUTTON", "Sign In");
?>