<?PHP 

	/**
	 * 
	 * pwplay.php english language file
	 *
	 * @author Ron MItchell
	 * @version 1.0
	 * @copyright Ron MItchell
	 * @package
	 */
	 
	define("PWPLAY_LOGON_FAIL","Sorry login has failed");

    define("XERTE_PWPLAY_DESCRIPTION", "Password Protected");

    define("XERTE_PWPLAY_GUIDANCE", "This resources is protected by a single unique password set by the author.");

define("XERTE_PWPLAY_LIGHTBOX", "View in lightbox");

    define("XERTE_PWPLAY_TEXTAREA_INSTRUCTIONS", "You have been asked to provide some feedback on this learning object. Please enter your feedback and click send when you have finished. This feedback is anonymous. If you wish to be contacted please add your name and contact details to your response before clicking send.");

    define("XERTE_PWPLAY_BUTTON_SEND", "Send");

    define("XERTE_PWPLAY_PASSWORD", "Password");

    define("XERTE_PWPLAY_LOGIN_BUTTON", "Sign In");
?>