<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

	define("RSS_DESCRIPTION","A feed containing all the public learning objects from");
	define("RSS_LANGUAGE","en-gb");
	define("RSS_DB_FAIL","Sorry, the system cannot connect to the database at present. The mysql error is ");
	define("RSS_LO","'s Learning Objects");
	define("RSS_PLURAL", "'s");
	define("RSS_FEED_DESC","A feed containing all of"); 
	define("RSS_FEED_PUBLIC","'s  public learning objects from the ");
	define("RSS_USER_LO","'s Learning Objects ");
	define("RSS_FEED_USER","A feed containing all of ");
	define("RSS_USER_LO_LOWER","'s learning objects - ");
	define("RSS_FROM","from the ");
	define("RSS_SITE","'s site ");
	define("RSS_DEVELOP","was developed by ");
 
 ?>