<?PHP 

	/**
	 * 
	 * rss english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("RSS_DESCRIPTION","A feed containing all the public learning objects from");
	define("RSS_LANGUAGE","en-gb");
	define("RSS_DB_FAIL","Sorry, the system cannot connect to the database at present. The mysql error is ");
	define("RSS_LO","'s Learning Objects");
	define("RSS_PLURAL", "'s");
	define("RSS_FEED_DESC","A feed containing all of"); 
	define("RSS_FEED_PUBLIC","'s  public learning objects from the ");
	define("RSS_USER_LO","'s Learning Objects ");
	define("RSS_FEED_USER","A feed containing all of ");
	define("RSS_USER_LO_LOWER","'s learning objects - ");
	define("RSS_FROM","from the ");
	define("RSS_SITE","'s site ");
	define("RSS_DEVELOP","was developed by ");
 
 ?>