<?PHP 

	/**
	 * 
	 * Syndicate english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("SYNDICATE_DESCRIPTION","This RSS feed contains a list of all the syndicated content from the Xerte Online Toolkits installation at ");
	define("SYNDICATE_LANGUAGE","en-gb");
	define("SYNDICATE_DOWNLOAD","Download this content from ");
	define("SYNDICATE_DOWNLOAD_SCORM","Download this as a scorm package from ");
	define("SYNDICATE_LICENCE","This content has the following license");

?>