<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
	 
	define("USER_SETTINGS_PASSWORD_TITLE","Change Password");
	define("USER_SETTINGS_PASSWORD_DISPLAY_TITLE","Change Password");

	define("USER_SETTINGS_PASSWORD_OLD", "Current Password");
	define("USER_SETTINGS_PASSWORD_NEW", "New Password");
	define("USER_SETTINGS_PASSWORD_NEW_REPEAT", "Repeat new Password");
    define("USER_SETTINGS_PASSWORD_SUBMIT", "Change password");

    define("USER_SETTINGS_EDITOR_OPEN_MODE", "Open editor in");
    define("USER_SETTINGS_EDITOR_OPEN_MODE_POPUP", "Open in a separate window");
    define("USER_SETTINGS_EDITOR_OPEN_MODE_BLANK", "Open in a new tab");
    define("USER_SETTINGS_EDITOR_OPEN_MODE_LIGHTBOX", "Open in an overlay on the overview page");

    define("USER_SETTINGS_PREFERENCES_TITLE", "My preferences");
    define("USER_SETTINGS_SECTION_EDITOR_OPEN", "When I open a lesson for editing");
    define("USER_SETTINGS_SECTION_OVERVIEW", "On my overview page");
    define("USER_SETTINGS_SECTION_IN_EDITOR", "In the editor");
    define("USER_SETTINGS_PANEL_EAST", "Show project templates on the right");
    define("USER_SETTINGS_PANEL_SOUTH", "Show the bar at the bottom");
    define("USER_SETTINGS_EDITOR_PANEL_EAST", "Show the help panel on the right");
    define("USER_SETTINGS_EDITOR_SHOW_LANGUAGE", "Show language options");
    define("USER_SETTINGS_EDITOR_SHOW_TOOLBAR", "Show edit buttons");
    define("USER_SETTINGS_EDITOR_EXPAND_GROUPS", "Open folders automatically");
    define("USER_SETTINGS_EDITOR_EXPAND_TREE", "Open content structure automatically");
    define("USER_SETTINGS_CANCEL", "Cancel");
    define("USER_SETTINGS_SAVE", "Save");

?>