<?PHP 

	/**
	 * 
	 * workspace properties english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
    define("PHP_ERROR","Status messages");
    define("WORKSPACE_PROPERTIES_TITLE","Workspace properties");
	define("WORKSPACE_PROPERTIES_DISPLAY_TITLE","Workspace Properties");
	define("WORKSPACE_PROPERTIES_TAB_DETAILS","My details");
	define("WORKSPACE_PROPERTIES_TAB_PROJECTS","My projects");
	define("WORKSPACE_PROPERTIES_TAB_FEEDS","My feeds");
	define("WORKSPACE_PROPERTIES_TAB_IMPORT","Import projects");
	define("WORKSPACE_PROPERTIES_TAB_API","API");
	
?>