<?PHP 

	/**
	 * 
	 * workspace properties english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
    define("PHP_ERROR","Status messages");
    define("WORKSPACE_PROPERTIES_TITLE","User workspace properties");
	define("WORKSPACE_PROPERTIES_DISPLAY_TITLE","Workspace Properties");
	define("WORKSPACE_PROPERTIES_TAB_DETAILS","My Details");
	define("WORKSPACE_PROPERTIES_TAB_PROJECTS","My Projects");
	define("WORKSPACE_PROPERTIES_TAB_FEEDS","My Feeds");
	define("WORKSPACE_PROPERTIES_TAB_IMPORT","Import");
	define("WORKSPACE_PROPERTIES_TAB_API","API");
	
?>