<?PHP     

	/**
	 * 
	 * management ai english language file
	 *
	 * @author Timo Boer
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("MANAGEMENT_SETTINGS", " settings");

    define("MANAGEMENT_VENDOR", " vendors");

	define("MANAGEMENT_ENABLE_VENDOR", "Allow usage of ");

    define("MANAGEMENT_KEY_STATUS", "Currently there is no valid API key associated with this vendor, please add one in vendor_config");

    define("MANAGEMENT_ENABLE_SUBOPTIONS", "Select the desired suboptions for ");

