<?PHP     

	/**
	 * 
	 * management ai english language file
	 *
	 * @author Timo Boer
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("MANAGEMENT_SETTINGS", " settings");

    define("MANAGEMENT_VENDOR", " vendors");

	define("MANAGEMENT_ENABLE_VENDOR", "Allow usage of ");

    define("MANAGEMENT_KEY_STATUS", "Currently there is no valid API key associated with this vendor, please add one in vendor_config");

    define("MANAGEMENT_ENABLE_SUBOPTIONS", "Select the desired suboptions for ");

    define("MANAGEMENT_AI_ADMIN_GUIDE_URL", "https://xot.xerte.org.uk/play_651");

    define("MANAGEMENT_AI_ADMIN_GUIDE_MESSAGE", "<h3>Manual & Advice</h3><p>For detailed and up-to-date instructions, including recommended vendor combinations, suggestions and advice, please refer to the Xerte AI admin reference and installation guide: </p>");

