<?PHP     

	/**
	 * 
	 * management delete template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("THEME_DISABLE_SUCCESS", "succeeded in disabling theme");

    define("THEME_ENABLE_SUCCESS", "succeeded in enabling theme");

    define("THEME_DISABLE_FAIL", "Failed to disable");

    define("THEME_ENABLE_FAIL", "Failed to enable");

    define("THEME_BAD_REQUEST", "Bad request, no matching fields");

    define("THEME_NO_ACCESS", "User does not have permission to delete themes");