<?PHP

	/**
	 * 
	 * management library english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("MANAGEMENT_LIBRARY_REMOVE", "Remove");
	define("MANAGEMENT_LIBRARY_VIEW", "View");	 

	define("MANAGEMENT_LIBRARY_ADD_CATEGORY", "Add a new category");
	define("MANAGEMENT_LIBRARY_NEW_CATEGORY", "The new category is");
	define("MANAGEMENT_LIBRARY_NEW_CATEGORY_NAME", "Enter name here");
	define("MANAGEMENT_LIBRARY_NEW_LABEL", "Add");
	define("MANAGEMENT_LIBRARY_EXISTING_CATEGORIES", "Manage existing categories");

	define("MANAGEMENT_LIBRARY_REMOVE_RSS", "Remove from RSS");
	define("MANAGEMENT_LIBRARY_REMOVE_EXPORT", "Remove from Export");
	define("MANAGEMENT_LIBRARY_REMOVE_SYNDICATION", "Remove from Syndication");

	define("MANAGEMENT_LIBRARY_ADD_SECURITY", "Add a new setting");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY", "The security setting's name is ");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_NAME", "Enter name here");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DATA", "The security data is ");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DETAILS", "Enter the web address or ip range");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_INFO", "The security info is ");
	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DESCRIPTION", "Enter the description users see here");

	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY", "Manage existing settings");
		
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_IS", "The security setting is ");
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_DATA", "The security data is ");
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_INFO", "The security info is ");
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_REMOVE", "Remove this setting");
	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_WARNING", "In removing a setting all content with this option will be set to Private. You should inform your users of this change first");
	
	define("MANAGEMENT_LIBRARY_NEW_LICENCE", "Add a new license");
	define("MANAGEMENT_LIBRARY_NEW_LICENCE_DETAILS", "The new license is ");
	define("MANAGEMENT_LIBRARY_NEW_LICENCE_NAME", "Enter license name here");
	define("MANAGEMENT_LIBRARY_MANAGE_LICENCES", "Manage existing licenses");

	define("MANAGEMENT_LIBRARY_FAIL", "the feature is for administrators only");

?>