<?PHP     

	/**
	 * 
	 * management site english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 *
	 * PLEASE USE DOUBLE QUOTES IN THESE FILES, OTHERWISE XERTE TRANS DOES NOT WORK!
	 *
	 */
	 

	define("MANAGEMENT_SITE_TITLE", "Site settings (HTML / Images)");

    define("MANAGEMENT_SITE_REGISTER_TEXT", "<p><h2>Register</h2></p><p>Please take the time to register this installation of Xerte Online Toolkits.</p><p>The register button below will take you to the Xerte Community Web Site to the Registration form. It will let you register this installation to the community.</p><p>You can choose to receive notifications about upcoming updates, and/or critical bug fixes.</p>");

    define("MANAGEMENT_SITE_REGISTER", "Register");

    define("MANAGEMENT_SITE_URL", "The site url is (This is the URL of the site - changing this will not change the URL)");

	define("MANAGEMENT_SITE_TITLE_HTML", "The site title is (This is the HTML title tag content) ");

	define("MANAGEMENT_SITE_NAME", "The site name is (This is part of index.php and the RSS and Syndication feeds)");

	define("MANAGEMENT_SITE_LOGO", "The site logo is (The logo in the top left)");

	define("MANAGEMENT_SITE_LOGO_ORG", "The organisational logo is (The logo in the top right)");

	define("MANAGEMENT_SITE_WELCOME", "The Welcome message is (The text above the tools on index.php)");

	define("MANAGEMENT_SITE_TEXT", "The site text is (The text to the right of the tools on index.php)");

	define("MANAGEMENT_SITE_NEWS", "The news text is (The second pod under the login pod on index.php)");

	define("MANAGEMENT_SITE_POD_ONE", "The content of pod one is (The first pod underneath the file area on the logged in page)");

	define("MANAGEMENT_SITE_POD_TWO", "The content of pod two is (The second pod underneath the file area on the logged in page)");

	define("MANAGEMENT_SITE_COPYRIGHT", "The copyright message is ");

	define("MANAGEMENT_SITE_DEMONSTRATION", "The demonstration page URL is ");

	define("MANAGEMENT_SITE_LOGIN_FORM", "The form string is (The code to handle the HTML format for the login box)");

	define("MANAGEMENT_SITE_PEER_FORM", "The Peer form string is (The code to handle the HTML format for the peer review login box)");

	define("MANAGEMENT_SITE_FEEDBACK", "The site's feedback list is (A semi-colon separated list of email addresses to receive feedback from the feedback page)");

	define("MANAGEMENT_SITE_SERVER", "Server Settings ");
		
	define("MANAGEMENT_VIEW", "Show");

	define("MANAGEMENT_SITE_HTACCESS", "The HTACCESS setting is (Whether or not you are using a .htaccess file on the site)");

	define("MANAGEMENT_SITE_SESSION_NAME", "The PHP session name is ");

	define("MANAGEMENT_SITE_MIME", "The allowed upload types for the Media and quota page are ");

	define("MANAGEMENT_SITE_INTEGRATION", "The integration config path is  ");

	define("MANAGEMENT_SITE_ADMIN_USER", "The admin username is ");

	define("MANAGEMENT_SITE_ADMIN_PASSWORD", "The admin password is ");

	define("MANAGEMENT_SITE_RSS", "RSS settings ");

	define("MANAGEMENT_SITE_RSS_TITLE", "The RSS Feed title is ");

	define("MANAGEMENT_SITE_RSS_PUBLISHER", "The institutional publisher as listed in the syndication feed is ");

	define("MANAGEMENT_SITE_RSS_RIGHTS", "The standard syndication rights for the syndicated content are ");

	define("MANAGEMENT_SITE_RSS_LICENCE", "The standard syndication license for the syndicated content is ");

	define("MANAGEMENT_SITE_PATH", "Path settings ");

	define("MANAGEMENT_SITE_PATH_MODULE", "The module path is ");

	define("MANAGEMENT_SITE_PATH_WEBSITE", "The website code path is ");

	define("MANAGEMENT_SITE_PATH_SHORT", "The short file area path is ");

	define("MANAGEMENT_SITE_PATH_LIBRARY", "The php library path is ");

	define("MANAGEMENT_SITE_PATH_ROOT", "The root file path is ");

	define("MANAGEMENT_SITE_PATH_IMPORT", "The import path is ");

	define("MANAGEMENT_SITE_SQL", "SQL query settings ");

	define("MANAGEMENT_SITE_QUERY", "The play edit preview query is ");
	
	define("MANAGEMENT_SITE_ERROR_HANDLING", "Error handling settings ");

	define("MANAGEMENT_SITE_ERROR_EMAIL", "The email error list is (Accounts to receive email messages from the error logger)");

	define("MANAGEMENT_SITE_ERROR_EMAIL_ACCOUNT", "The error log message is (Set to true to log errors)");

	define("MANAGEMENT_SITE_ERROR_MAX", "The maximum error size is (The maximum number of entries per error log)");

	define("MANAGEMENT_SITE_LDAP", "LDAP settings ");
	
	define("MANAGEMENT_SITE_LDAP_DELIMIT", "You can set up multiple hosts by separating entries in each of these fields with the $$$ string as a delimiter");

	define("MANAGEMENT_SITE_LDAP_HOST", "The ldap host is ");

	define("MANAGEMENT_SITE_LDAP_PORT", "The ldap port is ");

	define("MANAGEMENT_SITE_LDAP_PASSWORD", "The ldap password is"); 

	define("MANAGEMENT_SITE_LDAP_BASE", "The ldap base is ");

	define("MANAGEMENT_SITE_LDAP_BIND", "The ldap bind is ");

	define("MANAGEMENT_SITE_LDAP_FILTER_ONE", "The LDAP main filter is ");

	define("MANAGEMENT_SITE_LDAP_FILTER_TWO", "The LDAP second filter is");

	define("MANAGEMENT_SITE_XERTE", "Xerte Settings ");

	define("MANAGEMENT_SITE_XERTE_SAVE", "The flash save path is ");

	define("MANAGEMENT_SITE_XERTE_UPLOAD", "The flash upload path is ");

	define("MANAGEMENT_SITE_XERTE_PREVIEW", "The flash preview check path is ");

	define("MANAGEMENT_SITE_XERTE_SKIN", "The flash flv skin is 	");

	define("MANAGEMENT_SITE_EMAIL", "Email ");

	define("MANAGEMENT_SITE_EMAIL_ACCOUNT", "The site email account is (you NEED to fill this in if you want to enable feedback and/or peer reviews.)");

	define("MANAGEMENT_SITE_EMAIL_HEADERS", "The site email extra headers is (use the * symbol to represent a new line)");

	define("MANAGEMENT_SITE_EMAIL_SUFFIX", "The site email to add to username is ");

	define("MANAGEMENT_SITE_PROXY", "The site's proxy host is ");

	define("MANAGEMENT_SITE_PROXY_PORT", "The site's proxy port is ");

	define("MANAGEMENT_SITE_PROXY_EXPLAINED", "By directly editing the rss proxy.php file (in the root folder), you can add up to 4 proxys and ports should you wish.");

  define("MANAGEMENT_SITE_AUTH_DETAILS", "Authentication settings");

  define("MANAGEMENT_SITE_AUTH_METHOD", "The authentication method to use");

  define("MANAGEMENT_SITE_LTI","LTI settings");
  
  define("MANAGEMENT_SITE_XAPI", "xAPI settings");
  
  define("MANAGEMENT_SITE_XAPI_ENDPOINT", "xAPI endpoint (url)");
  
  define("MANAGEMENT_SITE_XAPI_KEY", "xAPI key (username)");
  
  define("MANAGEMENT_SITE_XAPI_SECRET", "xAPI secret (password)");

define("LTI_TOGGLE","View");

define("LTI_KEYS_NAME","LTI Key Descriptive Name");
define("LTI_KEYS_KEY","The LTI Key");
define("LTI_KEYS_SECRET","The LTI Keys Secret");
define("LTI_KEYS_CONTEXT_ID","An overide for the LTI Context");
define("LTI_KEYS_DELETED","When was this delete");
define("LTI_KEYS_UPDATED_ON","When was this last updated");

define("MANAGEMENT_SITE_LTI_KEYS","LTI Keys");

define("LTI_KEYS_NEW","New");
define("LTI_KEYS_DELETE","Delete");
define("LTI_KEYS_ADD","Add New LTI Key");
define("LTI_KEYS_ADD_SUBMIT","Add New LTI Key");
define("LTI_KEYS_EDIT_SUBMIT","Save LTI Key");
define("LTI_KEYS_DELETE_SUBMIT","Delete LTI Key");

?>