<?PHP     

	/**
	 * 
	 * management templates sync english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("SYNC_INSTALL", "template installed");

	define("SYNC_UPDATE", "template updated");
	
	define("SYNC_REQUIRES", " module cannot be installed as it requires ");
	
	define("SYNC_RETURN", "Click on central templates to return to the template management page");

?>