<?PHP

	/**
	 * 
	 * management template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("TEMPLATE_UPLOAD", "Upload a template");

	define("TEMPLATE_UPLOAD_BUTTON", "Upload");

	define("TEMPLATE_VIEW", "View");

	define("TEMPLATE_UPDATE", "Update template list");
	
	define("TEMPLATE_MANAGE", "Manage Existing templates");

	define("TEMPLATE_TYPE", "This template is of type");

	define("TEMPLATE_VERSION", "This template is version number"); 

	define("TEMPLATE_DESCRIPTION", "The description for this template is"); 

	define("TEMPLATE_UPLOAD_DATE", "This template was uploaded on");

	define("TEMPLATE_NAME", "The template has the following name for users");

	define("TEMPLATE_EXAMPLE", "The template has the following example (0 means no example)");

	define("TEMPLATE_ACCESS", "The following users can access this template (* means everyone)");

	define("TEMPLATE_DATE_UPLOAD", "The date uploaded for this template is (altering this affects the order they are displayed / most recent first");

	define("TEMPLATE_STATUS", "This template is currently set as");

	define("TEMPLATE_ACTIVE", "Active");

	define("TEMPLATE_INACTIVE", "Inactive");

	define("TEMPLATE_REPLACE", "Upload a new version of this template");


?>