<?PHP

	/**
	 * 
	 * management template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("TEMPLATE_UPLOAD", "Upload a template");

	define("TEMPLATE_UPLOAD_BUTTON", "Upload");

	define("TEMPLATE_VIEW", "Show");

    define("TEMPLATE_UPDATE_EXPLANATION", "<h2>Parent templates</h2><p>To add a template to your xot installation, please upload the template using ftp and press the button below to update.</p>");

	define("TEMPLATE_UPDATE", "Update template list");
	
	define("TEMPLATE_MANAGE", "<h2>Manage Existing templates</h2>");

	define("TEMPLATE_TYPE", "This template is of type");

	define("TEMPLATE_SUB_TYPE", "This template is a sub-type of");

	define("TEMPLATE_SUB_DELETE", "Delete");
	
	define("TEMPLATE_INSTALL", " This template relies on the module ");
	
	define("TEMPLATE_INSTALL_INST", " Please install ");

	define("TEMPLATE_VERSION", "This template is version number"); 

	define("TEMPLATE_DESCRIPTION", "The description for this template is"); 

	define("TEMPLATE_UPLOAD_DATE", "This template was uploaded on");

	define("TEMPLATE_NAME", "The template has the following name for users");

	define("TEMPLATE_EXAMPLE", "The template has the following example (0 means no example)");

	define("TEMPLATE_ACCESS", "The following users can access this template (* means everyone)");

	define("TEMPLATE_DATE_UPLOAD", "The date uploaded for this template is (altering this affects the order they are displayed / most recent first");

	define("TEMPLATE_STATUS", "This template is currently set as");

	define("TEMPLATE_ACTIVE", "Active");

	define("TEMPLATE_INACTIVE", "Inactive");

	define("TEMPLATE_REPLACE", "Upload a new version of this template");

	define("TEMPLATE_SUB_PAGES", "Select the pages that can be used in the 'Simple' mode of the wizard. If all pages are selected (default), than the 'Simple' mode of the editor is disabled.");

	define("TEMPLATE_SUB_PAGES_SELECT_ALL", "Toggle all pages on or off");

	define("TEMPLATE_ADD_EXPLANATION", "<h2>Sub-templates</h2><p>Import an exported learning object as a new sub-template. If the sub-template already exists it will be replaced. The 'Template name' field identifies the sub-template. The 'Template display name' is the name shown to the user.</p><p>Do not use spaces or any other special characters in the template name, as this name is used as a foldername. If you do use special characters or spaces, these will be replaced by  a '_' character.</p>");

    define("TEMPLATE_ADD", "Add template");

    define("TEMPLATE_UPLOAD_FILE", "Upload file");

    define("TEMPLATE_UPLOAD_TEMPLATENAME", "Enter the template name");

    define("TEMPLATE_UPLOAD_TEMPLATEDISPLAYNAME", "Enter the template display name");

    define("TEMPLATE_UPLOAD_TEMPLATEDESCRIPTION", "Enter the template description");


?>