<?PHP     

	/**
	 * 
	 * management delete template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

    define("THEME_NO_ACCESS", "Access denied");

    define("THEME_BAD_REQUEST", "Bad request, unknown theme");

	define("MANAGEMENT_DELETE_SUCCESS", "succeeded in deleting");

	define("MANAGEMENT_DELETE_FAIL", "Failed to delete");
	
