<?PHP

	/**
	 * 
	 * management template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

    define("MANAGEMENT_THEMES_DEFAULTS", "Default themes");

    define("MANAGEMENT_THEMES_DEFAULT_XERTE", "The default theme for new Xerte Online Toolkits learning objects");

    define("MANAGEMENT_THEMES_DEFAULT_SITE", "The default theme for new Bootstrap learning objects");

    define("MANAGEMENT_THEMES_DEFAULT_DECISION", "The default theme for new Decision learning objects");

    define("MANAGEMENT_THEMES_MANAGE", "Manage and install themes");

    define("MANAGEMENT_THEMES_INSTALL_THEME", "Upload and install a new theme");

    define("MANAGEMENT_THEMES_UPLOAD_ZIP", "The theme zipfile should be a zipfile with one folder in it with the name of the theme or a zip file with only the contents of the actual theme. The theme identifier will be taken from the .info file.");

	define("MANAGEMENT_THEMES_UPLOAD_BUTTON", "Upload");

    define("MANAGEMENT_THEMES_UPLOAD_THEMETYPE", "Select the theme type");

    define("MANAGEMENT_THEMES_SHOW", "Show");

    define("MANAGEMENT_THEMES_BTN_ENABLE", "Enable theme");

    define("MANAGEMENT_THEMES_BTN_DISABLE", "Disable theme");

    define("MANAGEMENT_THEMES_ENABLE_DISABLE", "Enable and/or disable themes. A disabled theme will not be shown in the theme selection of a project.");
