<?php
/**
 * Created by PhpStorm.
 * User: Akshay
 * Date: 10/24/2018
 * Time: 4:01 PM
 */

define("THEME_UPLOAD_NO_FILE_SELECTED", "There is no file selected!");

define("THEME_UPLOAD_INCORRECT_FILE_TYPE", "The file you are trying to upload is not a .zip file. Please try again!");

define("THEME_UPLOAD_HAS_NO_INFO", "The .zip file doesn't contain an .info file!");

define("THEME_UPLOAD_FILE_CANT_BE_UPLOADED", "Something went wrong with moving the current zip file! Please try again!");

define("THEME_UPLOAD_WRONG_STRUCT", "The file you are trying to upload is not of the allowed structures");

define("THEME_UPLOAD_FILE_UPLOAD_SUCCESS", "The theme object has been imported successfully!");

