<?php
/**
 * Created by PhpStorm.
 * User: Akshay
 * Date: 10/24/2018
 * Time: 4:01 PM
 */

    define("UPLOAD_INCORRECT_FILE_TYPE", "The file you are trying to upload is not a .zip file. Please try again!");

    define("UPLOAD_CORRECT", "The file has been extracted successfully!");

    define("UPLOAD_ERROR", "The file hasn't been uploaded successfully!, please try again/");

    define("UPLOAD_HAS_NO_TEMPLATE_XML", "The .zip file doesn't contain a template.xml!");

    define("UPLOAD_HAS_NO_MEDIA", "The .zip file doesn't contain a media folder!");

    define("EMPTY_DESCRIPTION", "Description can't be empty!");

    define("FILE_CANT_BE_UPLOADED", "Something went wrong with moving the current zip file! Please try again!");

    define("FILE_UPLOAD_SUCCESS", "File uploaded successfully!");
?>