<?php
/**
 * Created by PhpStorm.
 * User: Akshay
 * Date: 10/24/2018
 * Time: 4:01 PM
 */

    define("UPLOAD_INCORRECT_FILE_TYPE", "The file you are trying to upload is not a .zip file. Please try again!");

    define("UPLOAD_CORRECT", "The file has been extracted succesfully!");

    define("UPLOAD_ERROR", "The file hasn't been uploaded succesfully!, please try again/");

    define("UPLOAD_HAS_NO_TEMPLATE_XML", "The .zip file has no template.xml!");
?>