<?php

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

define("THEME_UPLOAD_NO_FILE_SELECTED", "There is no file selected!");

define("THEME_UPLOAD_INCORRECT_FILE_TYPE", "The file you are trying to upload is not a .zip file. Please try again!");

define("THEME_UPLOAD_HAS_NO_INFO", "The .zip file doesn't contain an .info file!");

define("THEME_UPLOAD_FILE_CANT_BE_UPLOADED", "Something went wrong with moving the current zip file! Please try again!");

define("THEME_UPLOAD_WRONG_STRUCT", "The file you are trying to upload is not of the allowed structures");

define("THEME_UPLOAD_FILE_UPLOAD_SUCCESS", "The theme object has been imported successfully!");

