<?PHP     

	/**
	 * 
	 * management users english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("USERS_TOGGLE", "View");

	define("USERS_ID", "The user's ID is ");

	define("USERS_FIRST", "The user's first name is ");

	define("USERS_KNOWN", "The user's surname is ");
	
	define("USERS_USERNAME", "The user's username is");
	
?>