<?PHP     

	/**
	 * 
	 * management users template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("USER_GROUPS_MANAGEMENT_SEARCH", "Search");

    define("USER_GROUPS_MANAGEMENT_MANAGE", "Manage existing groups");
	
    define("USER_GROUPS_MANAGEMENT_SELECT_GROUP", "Select Group");

	define("USER_GROUPS_MANAGEMENT_ADD", "Add a new group");

    define("USER_GROUPS_MANAGEMENT_ADD_GROUP", "Create New Group");

    define("USER_GROUPS_MANAGEMENT_REMOVE_GROUP", "Delete Group");

	define("USER_GROUPS_MANAGEMENT_ALL_USERS", "All active users with Learning Objects");

    define("USER_GROUPS_MANAGEMENT_SELECT", "Select user(s).");

	define("USER_GROUPS_MANAGEMENT_GROUP_MEMBERS", "All members of ");

	define("USER_GROUPS_MANAGEMENT_ADD_MEMBER", "Add user(s) to selected group");

	define("USER_GROUPS_MANAGEMENT_REMOVE_MEMBER", "Remove user from group");

	define("USER_GROUPS_MANAGEMENT_NO_MEMBERS", "This group currently has no members.");

    define("USER_GROUPS_MANAGEMENT_ONE_MEMBER", "This group currently has 1 member:");

    define("USER_GROUPS_MANAGEMENT_MEMBERS_COUNT", "This group currently has {n} members:");

    define("USER_GROUPS_MANAGEMENT_GROUP_EXISTS", "This group name is already in use.");

?>
