<?PHP

/**
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.

 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

define("USER_GROUPS_MANAGEMENT_SEARCH", "Search");

define("USER_GROUPS_MANAGEMENT_MANAGE", "Manage existing groups");

define("USER_GROUPS_MANAGEMENT_SELECT_GROUP", "Select Group");

define("USER_GROUPS_MANAGEMENT_ADD", "Add a new group");

define("USER_GROUPS_MANAGEMENT_ADD_GROUP", "Create New Group");

define("USER_GROUPS_MANAGEMENT_RENAME_GROUP", "Rename Group");

define("USER_GROUPS_MANAGEMENT_RENAME_GROUP_PROMPT", "Enter a new group name for");

define("USER_GROUPS_MANAGEMENT_REMOVE_GROUP", "Delete Group");

define("USER_GROUPS_MANAGEMENT_ALL_USERS", "All active users with Learning Objects");

define("USER_GROUPS_MANAGEMENT_SELECT", "Select user(s).");

define("USER_GROUPS_MANAGEMENT_GROUP_MEMBERS", "All members of ");

define("USER_GROUPS_MANAGEMENT_ADD_MEMBER", "Add user(s) to selected group");

define("USER_GROUPS_MANAGEMENT_REMOVE_MEMBER", "Remove user from group");

define("USER_GROUPS_MANAGEMENT_NO_MEMBERS", "This group currently has no members.");

define("USER_GROUPS_MANAGEMENT_ONE_MEMBER", "This group currently has 1 member:");

define("USER_GROUPS_MANAGEMENT_MEMBERS_COUNT", "This group currently has {n} members:");

define("USER_GROUPS_MANAGEMENT_GROUP_EXISTS", "This group name is already in use.");

?>