<?PHP     

	/**
	 * 
	 * management users english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("USERS_TOGGLE", "Show");

	define("USERS_ID", "The user's ID is ");

	define("USERS_FIRST", "The user's first name is ");

	define("USERS_KNOWN", "The user's surname is ");
	
	define("USERS_USERNAME", "The user's username is");

    define("USERS_MANAGE_AUTH", "Authorized users");

    define("USERS_MANAGE_ACTIVE", "Active users with Learning Objects");

	define("USERS_ROLES_SUCCESS", "Success");
	
	define("USERS_FAILED_REMOVE_ROLES", "Failed to remove roles");
	
	define("USERS_FAILED_ADD_ROLES", "Failed to add roles");
	
	define("USERS_MODIFY_ROLES", "Modify user roles");

    define("USERS_MANAGE_ROLES", "Manage user roles");

    define("USERS_ROLE_SUPER", "Super Admin");

    define("USERS_ROLE_SYSTEM", "System Admin");
    
    define("USERS_ROLE_TEMPLATEADMIN", "Template Admin");
    
    define("USERS_ROLE_METAADMIN", "Meta Admin");
    
    define("USERS_ROLE_USERADMIN", "User Admin");
    
    define("USERS_ROLE_PROJECTADMIN", "Project Admin");
