<?PHP     

	/**
	 * 
	 * management users template english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("USERS_MANAGEMENT_TEMPLATE_VIEW", "View");		 

	define("USERS_MANAGEMENT_TEMPLATE_ID", "The template id is");

	define("USERS_MANAGEMENT_TEMPLATE_CREATED", "The date created was"); 

	define("USERS_MANAGEMENT_TEMPLATE_MODIFIED", "The date modified was"); 

	define("USERS_MANAGEMENT_TEMPLATE_ACCESSED", "The date accessed was");

	define("USERS_MANAGEMENT_TEMPLATE_PLAYS", "The number of plays is"); 

	define("USERS_MANAGEMENT_TEMPLATE_ACCESS", "Access for this is set as"); 	

	define("USERS_MANAGEMENT_TEMPLATE_EDIT", "Edit");

    define("USERS_MANAGEMENT_TEMPLATE_PREVIEW", "Preview");

	define("USERS_MANAGEMENT_TEMPLATE_PROPERTIES", "Properties");				

	define("USERS_MANAGEMENT_TEMPLATE_GIVE", "Give this template to another user");

	define("USERS_MANAGEMENT_TEMPLATE_GIVE_BUTTON", "Give template");

	define("USERS_MANAGEMENT_TEMPLATE_NONE", "This user has no templates at present");

    define("USERS_MANAGEMENT_TEMPLATE_OWNER", "Owner");

    define("USERS_MANAGEMENT_TEMPLATE_ROLE", "Role");
?>