<?PHP     

	/**
	 * 
	 * management users english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 

	define("USERS_TOGGLE", "Show");

	define("USERS_ID", "The user's ID is ");

	define("USERS_FIRST", "The user's first name is ");

	define("USERS_KNOWN", "The user's surname is ");
	
	define("USERS_USERNAME", "The user's username is");

    define("USERS_MANAGE_AUTH", "Authorized users");

    define("USERS_MANAGE_ACTIVE", "Active users with Learning Objects");

	define("USERS_ROLES_SUCCESS", "Success");
	
	define("USERS_FAILED_REMOVE_ROLES", "Failed to remove roles");
	
	define("USERS_FAILED_ADD_ROLES", "Failed to add roles");
	
	define("USERS_MODIFY_ROLES", "Modify user roles");

    define("USERS_MANAGE_ROLES", "Manage user roles");
    define("USERS_MANAGE_ROLES_ASSIGN_ROLES", "Assign and edit user roles");
    define("USERS_MANAGE_ROLES_OVERVIEW", "Currently assigned roles");
    define("USERS_MANAGE_ROLES_OVERVIEW_USERNAME", "User");
    define("USERS_MANAGE_ROLES_OVERVIEW_ASSIGNED_ROLES", "Assigned roles");
    define("USERS_MANAGE_ROLES_OVERVIEW_SELECT_USER", "Select this user to modify their roles");

//  admin roles human names -------------------------------------------
    define("USERS_ROLE_SUPER", "Super Admin");

    define("USERS_ROLE_SYSTEM", "System Admin");
    
    define("USERS_ROLE_TEMPLATEADMIN", "Template Admin");
    
    define("USERS_ROLE_METAADMIN", "Meta Admin");
    
    define("USERS_ROLE_USERADMIN", "User Admin");
    
    define("USERS_ROLE_PROJECTADMIN", "Project Admin");

    define("USERS_ROLE_HARVESTADMIN", "Harvest Admin");
//  admin roles info -------------------------------------------

    define("USERS_ROLE_SUPER_INFO", "This role gives access to the whole management page. It is the highest level of access.");

    define("USERS_ROLE_SYSTEM_INFO", "This role gives access to the Site, Log Files, Play security, Licenses and Feeds tabs in the management page.");
    
    define("USERS_ROLE_TEMPLATEADMIN_INFO", "This role gives access to the Templates and Themes tabs in the management page.");
    
    define("USERS_ROLE_METAADMIN_INFO", "This role gives access to the Categories, Educations, Groupings and Courses tabs in the management page.");
    
    define("USERS_ROLE_USERADMIN_INFO", "This role gives access to the Users and User Groups tabs in the management page.");
    
    define("USERS_ROLE_PROJECTADMIN_INFO", "This role gives access to the User Projects tab in the management page.");

    define("USERS_ROLE_HARVESTADMIN_INFO", "This role allows you to enable a project to be harvested using OAI-PMH (if configured).");

