<?PHP     

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("DISPLAY_RECYCLE", "Kosz");
	
	define("DISPLAY_EXAMPLE", "Zobacz przykład");
	
	define("DISPLAY_CREATE", "Utwórz");

    define("DISPLAY_BUTTON_PROJECT_CREATE", "Utwórz projekt");

    define("DISPLAY_NAME", "Wprowadź nazwę dla tego projektu");
	
	define("DISPLAY_ERROR", "Wystąpił błąd i w tym momencie nie możesz edytować");
	
	define("DISPLAY_EDITED", "Ten plik jest obecnie edytowany przez ");
	
	define("DISPLAY_LOCKFILE_MESSAGE", "Jeżeli jesteś pewny że to nie przypadek, możesz kliknąć na poniższy przycisk w celu edycji pliku. Jeżeli będziesz kontynuował podczas kiedy dwie osoby będą edytować plik w tym samym czasie, istnieje ryzyko uszkodzenia pliku. Jednakże, prosimy poczekać do momentu, aż obecny edytor zamknie plik i stworzy sytuację, że będzie można bezpiecznie edytować plik.");
	
	define("DISPLAY_LOCKFILE_DELETE", "Usuń blokadę pliku");

    define("DISPLAY_WORKSPACE","Obszar roboczy");


?>