<?PHP   

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("WORKSPACE_LIBRARY_MY", "Moje projekty");

	define("WORKSPACE_LIBRARY_SHARED", "Udostępnione projekty");
	
	define("WORKSPACE_LIBRARY_PUBLIC", "Publiczne projekty");
	
	define("WORKSPACE_LIBRARY_USAGE", "Statystyki użycia");
	
	define("WORKSPACE_LIBRARY_RSS", "Projekty w RSS");
	
	define("WORKSPACE_LIBRARY_OPEN", "Otwarta zawartość projektów");
	
	define("WORKSPACE_LIBRARY_PEER", "Wzajemny przegląd");
	
	define("WORKSPACE_LIBRARY_XML", "Udostępnianie XML");

	define("WORKSPACE_LIBRARY_TEMPLATE_NAME", "Nazwa");
		
?>