<?PHP   

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("IMPORT_NAME_IF_EMPTY","Zaimportwano szablon");
	
	define("IMPORT_SUCCESS","Nowy szablon został zaimportowany");
	
	define("IMPORT_SUCCESS_REPLACE","Szablon pomyślnie zastąpiony");
	
	define("IMPORT_OWNER_FAIL","Tylko właściciel tego szablonu może importować na górę");

	define("IMPORT_FTP_FAIL","Transfer pliku niepowiódł się");

	define("IMPORT_TYPE_FAIL","Przepraszamy, nie można uzyskać typu dla tego szablonu");

	define("IMPORT_NO_EQUIVALENT_FAIL","Nie znaleziono poprawnego szablonu na tej stronie. Proszę skontakować się z administratorem systemu.");

	define("IMPORT_ZIP_FAIL","Możesz tylko importować pliki ZIP");
	
	define("IMPORT_XERTE_ONLY","Tylko szablony Xerte są obecnie importowane");
	
	define("IMPORT_ZIP_FOLDER_LEVEL","Pliki w twoim folderze zip muszą być w głównym folderze, a nie w innym folderze zip.");

    define("IMPORT_NOT_WRITABLE", "Folder potrzebuje uprawnień do zapisu.")


?>