<?PHP 

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("IMPORT_TEMPLATE_ZIP_FAIL","Plik ZIP ma niepoprawną konstrukcję");
	
	define("IMPORT_TEMPLATE_TEMPLATE_FAIL","Szablon nie jest poprawnie ustawiony do pracy z narzędziami");
	
	define("IMPORT_TEMPLATE_RLT_FAIL","Nie znaleziono pliku template.rlt");
	
	define("IMPORT_TEMPLATE_FOLDER_CREATE","Folder został utworzony");

	define("IMPORT_TEMPLATE_FOLDER_FAIL","Błąd podczas tworzenia folderu");
	
}
