<?PHP   

/**
 * Polish
 * Translated by: Jarosław Maciejewski <nitro.bystrzyca@gmail.com>
 */

	define("FEEDBACK_TITLE","Witamy w Narzędziach Online Xerte");
	define("FEEDBACK_RESPONSE","Diękujemy za twoją wiadomość");
	define("FEEDBACK_EMAIL_TITLE","Xerte Online Wiadomość");
	define("FEEDBACK_GIVER","Nazwa ");
	define("FEEDBACK_MESSAGE_INTRO","Wiadomość");
	define("FEEDBACK_PAGE_TITLE","Witamy na stronie kontaktowej Narzędzi Online Xerte");
	define("FEEDBACK_DESCRIPTION","Proszę zostawić tutaj swoją wiadomość. Wszystkie wiadomości są anonimowe, jednakże jeżeli oczekujesz odpowiedzi zostaw w poniższym bloku swoje imię i jakiś kontakt do siebie.");
	define("FEEDBACK_TEXTAREA","Wiadomość");
	define("FEEDBACK_BUTTON","Wyślij wiadomość");

?>